/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Clientes.java
 *
 * Created on 13/03/2011, 18:46:50
 */

package Interface;

import Modelo.Clientes;
import Modelo.ConexaoBD;
import Controle.Controla_Clientes;
import Ferramentas.CaixaDeDialogo;
import Ferramentas.Cronometro;
import Ferramentas.Formatacao;
import Ferramentas.Validacao;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;

/**
 *
 * @author Jonas
 */
public class Tela_Principal extends javax.swing.JFrame {
     Menu objMenu;
     public static Connection con;
     public static Statement stmt;
     public boolean vSelecao = true;
     //Clientes objCliente = null;
     Controla_Clientes ctlCliente;
     Clientes Clientes = new Clientes();
          
    /** Creates new form Clientes */
    public Tela_Principal(String pPesquisa) {
        abreConexao();
        this.setLocation(20, 100);
        initComponents();

        ButtonGroup bg= new ButtonGroup();
        bg.add(rbComecandoPor); // jRadioButton1
        bg.add(rbContendo); // jRadioButton2

        LimpaTela(true,false);
        txtCampoPesquisa.setText(pPesquisa);
        
        System.out.print("pPesquisa = " + pPesquisa);
        cbPesquisarPor.setSelectedItem("Nome_Cliente");
        btPesquisarActionPerformed(null);
        

    }

//    public Clientes(Clientes objCliente) {
//        this.objCliente = objCliente;
//    }


    private void abreConexao() {
        try {
        con = ConexaoBD.getInstance().getConnection();
        stmt = con.createStatement();
        System.out.print("Conexão com Banco de Dados Criada!");
        } catch (Exception e) {
        System.out.print(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        tbpClientes = new javax.swing.JTabbedPane();
        pnlConsulta = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        rbComecandoPor = new javax.swing.JRadioButton();
        rbContendo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtgClientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbPesquisarPor = new javax.swing.JComboBox();
        txtCampoPesquisa = new javax.swing.JTextField();
        pnlManutencao = new javax.swing.JLayeredPane();
        jpManutencao = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dtgResultados = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId_Prova = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtData_Criacao = new javax.swing.JFormattedTextField();
        txtTelefone_Cliente = Formatacao.getTelefone();
        jLabel4 = new javax.swing.JLabel();
        txtEndereco_Cliente = new javax.swing.JTextField();
        txtNome_Cliente = new javax.swing.JTextField();
        btNovo1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btNovo2 = new javax.swing.JButton();
        lblTimer = new javax.swing.JLabel();
        btExcluir1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lblLista1 = new javax.swing.JLabel();
        lblLista2 = new javax.swing.JLabel();
        lblLista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        setPreferredSize(new java.awt.Dimension(653, 458));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Confirma.png"))); // NOI18N
        btAdicionar.setText("Adicionar");
        btAdicionar.setPreferredSize(new java.awt.Dimension(77, 25));
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Lapis2.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setPreferredSize(new java.awt.Dimension(77, 25));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Novo.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setPreferredSize(new java.awt.Dimension(77, 25));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Porta.PNG"))); // NOI18N
        btFechar.setText("Fechar");
        btFechar.setPreferredSize(new java.awt.Dimension(77, 25));
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Exclui.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setPreferredSize(new java.awt.Dimension(77, 25));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Mais.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovo)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 11, 633, 47);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        rbComecandoPor.setSelected(true);
        rbComecandoPor.setText("Começando Por");
        rbComecandoPor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbComecandoPorStateChanged(evt);
            }
        });

        rbContendo.setText("Contendo");
        rbContendo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbContendoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rbContendo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbComecandoPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbComecandoPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(rbContendo)
                .addContainerGap())
        );

        pnlConsulta.add(jPanel2);
        jPanel2.setBounds(430, 10, 190, 90);
        jPanel2.getAccessibleContext().setAccessibleName("Seleção");

        dtgClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dtgClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtgClientesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dtgClientesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(dtgClientes);

        pnlConsulta.add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 610, 240);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jLabel8.setText("Pesquisar Por");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPesquisar))
                    .addComponent(txtCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlConsulta.add(jPanel3);
        jPanel3.setBounds(10, 10, 420, 90);

        tbpClientes.addTab("Consulta", pnlConsulta);

        pnlManutencao.setEnabled(false);

        jpManutencao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpManutencao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        dtgResultados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dtgResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtgResultadosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dtgResultadosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(dtgResultados);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpManutencao.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 260, 310));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel2.setText("Id");

        txtId_Prova.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId_Prova.setEnabled(false);

        jLabel5.setText("Data");

        txtData_Criacao.setEditable(false);

        jLabel4.setText("Equipe");

        txtEndereco_Cliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtNome_Cliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Mais.png"))); // NOI18N
        btNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtId_Prova, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtData_Criacao, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtEndereco_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtNome_Cliente)))
                .addGap(118, 118, 118)
                .addComponent(btNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId_Prova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData_Criacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndereco_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovo1))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jpManutencao.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 90));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Prova"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btNovo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btNovo2.setText("INICIAR TIMER");
        btNovo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo2ActionPerformed(evt);
            }
        });
        jPanel6.add(btNovo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, 45));

        lblTimer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimer.setText("10");
        jPanel6.add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 60, 40));

        btExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Exclui.png"))); // NOI18N
        btExcluir1.setText("INFORMAR PROBLEMA");
        btExcluir1.setPreferredSize(new java.awt.Dimension(77, 25));
        btExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluir1ActionPerformed(evt);
            }
        });
        jPanel6.add(btExcluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 260, -1));

        jpManutencao.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 320, 110));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Próximas Equipes"));
        jPanel7.setLayout(null);

        lblLista1.setText("3 - Equipe Charli");
        jPanel7.add(lblLista1);
        lblLista1.setBounds(160, 20, 140, 20);

        lblLista2.setText("1 - Equipe Alfa");
        jPanel7.add(lblLista2);
        lblLista2.setBounds(10, 20, 140, 20);

        lblLista.setText("2 - Equipe Delta");
        jPanel7.add(lblLista);
        lblLista.setBounds(10, 40, 140, 20);

        jpManutencao.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 320, 80));

        pnlManutencao.add(jpManutencao);
        jpManutencao.setBounds(10, 10, 610, 330);

        tbpClientes.addTab("Manutenção", pnlManutencao);

        getContentPane().add(tbpClientes);
        tbpClientes.setBounds(10, 69, 633, 378);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int wControle = 0;

        wControle = Tela_Login.objMenu.preencheJanelas("Clientes", "I");
            if (wControle != 0){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Clientes'");
            }
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        int wControle = 0;
//
//        wControle = Tela_Login.objMenu.preencheJanelas("Clientes", "I");
//            if (wControle != 0){
//            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Clientes'");
//            }
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        int wControle = 0;

        wControle = Tela_Login.objMenu.preencheJanelas("Clientes", "I");
            if (wControle != 0){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Clientes'");
            }
        dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        int wControle = 0;
        String xMensagemValidacao = "";

        xMensagemValidacao = ValidaDados();
        if (xMensagemValidacao.equals("")){
        System.out.println("Validou Dados");

        Clientes.definirId_Cliente(Integer.parseInt(txtId_Prova.getText()));
        //Clientes.definirNome_Cliente(txtNome_Cliente.getText());
        //Clientes.definirTelefone(txtTelefone_Cliente.getText().replace("(","").replace(")","").replace("-",""));
        GuardaDados(false);
        System.out.println("Guardou Dados");

        wControle = ctlCliente.alterarCliente();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Cliente alterado com sucesso!");
           LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao alterar cliente!");
           }
        } else {
        CaixaDeDialogo.obterinstancia().exibirMensagem("Erros de Validação: \n" + xMensagemValidacao);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        LimpaTela(true,false);
    }//GEN-LAST:event_btLimparActionPerformed

    private void dtgClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgClientesMouseClicked
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_dtgClientesMouseClicked

    private void dtgClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgClientesMousePressed
        // TODO add your handling code here:
        int wControle;
        int linhaSelecionada = dtgClientes.getSelectedRow();//pega a linha selecionada
        String coluna1 = dtgClientes.getModel().getValueAt(linhaSelecionada, 0).toString(); // Primeira coluna da linha
        
        if (dtgClientes.isColumnSelected(3)){
            tbpClientes.setSelectedIndex(1);
            txtNome_Cliente.requestFocus();
            btAlterar.setVisible(true);
            btExcluir.setVisible(true);
            btNovo.setVisible(true);
            btAdicionar.setVisible(false);

            ctlCliente = new Controla_Clientes(Clientes, dtgClientes);

            Clientes.definirId_Cliente(Integer.parseInt(coluna1));
            wControle = ctlCliente.buscarCliente();
                if (wControle < 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao buscar Cliente no BD!");
                } else {
                if (wControle == 0)
                TelaAlteracao();
                }
     }
    }//GEN-LAST:event_dtgClientesMousePressed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        int wControle = 0;
        String xMensagemValidacao = "";
        
        xMensagemValidacao = ValidaDados();
        if (xMensagemValidacao.equals("")){
        System.out.println("Validou Dados");
        GuardaDados(true);
        System.out.println("Guardou Dados");

        wControle = ctlCliente.gravarCliente();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Cliente gravado com sucesso!");
            LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao gravar cliente!");
           }
        } else {
        CaixaDeDialogo.obterinstancia().exibirMensagem("Erros de Validação: \n" + xMensagemValidacao);
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int wControle = 0;

        char wChar = 'p';
        boolean wPergunta = false;

        wPergunta = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Tem certeza de que deseja excluir o Cliente?","",wChar);

        if (wPergunta == true){
        Clientes.definirId_Cliente(Integer.parseInt(txtId_Prova.getText()));
        Clientes.definirUsuario_Exclusao(Tela_Login.objMenu.mIdUsuarioLogin);
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        formatador.format(data);
        Clientes.definirData_Exclusao(formatador.format(data));
        wControle = ctlCliente.excluirCliente();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Cliente excluído com sucesso!");
           LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao excluir cliente!");
          }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        String pTipoSelecao = "";
        if (rbComecandoPor.isSelected()){
           pTipoSelecao = "CP";
        } else {
           pTipoSelecao = "CT";
        }

        ctlCliente.PreencheClientes(cbPesquisarPor.getSelectedItem().toString(),txtCampoPesquisa.getText(), pTipoSelecao);
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void rbComecandoPorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbComecandoPorStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbComecandoPorStateChanged

    private void rbContendoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbContendoStateChanged
        // TODO add your handling code here:
        //rbComecandoPor.setSelected(false);
        //rbContendo.setSelected(true);
    }//GEN-LAST:event_rbContendoStateChanged

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        LimpaTela(true,true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNovo1ActionPerformed

    private void dtgResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgResultadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dtgResultadosMouseClicked

    private void dtgResultadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgResultadosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtgResultadosMousePressed

    private void btNovo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo2ActionPerformed

    }//GEN-LAST:event_btNovo2ActionPerformed

    private void btExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluir1ActionPerformed

    private void AtualizaClientes(){
        //objClientes.setNome(txNomeMotorista.getText());
        //objClientes.definirNome_Cliente('teste');
        //objClientes.definirTelefone('teste');
        //objClientes.setCategoriaCarteira('teste');
        ctlCliente = new Controla_Clientes(Clientes, dtgClientes);
        
        //wControle = objClientes_Implem.buscaClientes();
        ctlCliente.PreencheClientes("","","");
        PreencheComboPesquisa();
    }

        private void PreencheComboPesquisa(){

        cbPesquisarPor.removeAllItems();
        if ((dtgClientes.getColumnCount() - 1) > 0){
            for (int i= 0; i < dtgClientes.getColumnCount() - 1; i++){
              cbPesquisarPor.addItem(dtgClientes.getColumnName(i));
            }
        }
        
    }

        private String ValidaDados() {
        String xMensagem = "";
        
        if(txtNome_Cliente.getText().equals("")){
        xMensagem +="Nome Cliente deve ser preenchido! \n";
        }

        if (txtTelefone_Cliente.getText().replace("(", "").replace(")","").replace("-","").replace(" ","").length() > 0){
        Validacao.validarTelefone(txtTelefone_Cliente);
            if (txtTelefone_Cliente.getText().replace("(", "").replace(")","").replace("-","").replace(" ","").length() == 0){
            xMensagem +="Telefone Cliente deve ser preenchido corretamente! \n";
            }
        }
        return xMensagem;
     }

        private void GuardaDados(boolean RegistroNovo) {

        if (RegistroNovo == true){
        System.out.println("Guardou Dados Registro Novo = true");
        Clientes.definirId_Cliente(0);
        Clientes.definirNome_Cliente(txtNome_Cliente.getText());
        Clientes.definirTelefone(txtTelefone_Cliente.getText().replace("(","").replace(")","").replace("-",""));
        Clientes.definirUsuario_Criacao(Tela_Login.objMenu.mIdUsuarioLogin);
        Clientes.definirData_Criacao(txtData_Criacao.getText());
        System.out.println("definirData_Criacao = " + txtData_Criacao.getText());
        //ctlCliente = new Controla_Clientes(Clientes, dtgClientes);
        } else {
        System.out.println("Guardou Dados Registro Novo = false");
        Clientes.definirNome_Cliente(txtNome_Cliente.getText());
        Clientes.definirTelefone(txtTelefone_Cliente.getText().replace("(","").replace(")","").replace("-",""));
        }
    }

    private void TelaAlteracao() {

        pnlManutencao.setEnabled(true);
        txtId_Prova.setText(Integer.toString(Clientes.obterId_Cliente()));
        txtNome_Cliente.setText(Clientes.obterNome_Cliente());
        txtTelefone_Cliente.setText(Clientes.obterTelefone());

        String data = Formatacao.ajustaDataDMA(Clientes.obterData_Criacao());
        txtData_Criacao.setText(data);
        
        if (Clientes.obterData_Exclusao() == null){
            txtSituacao.setText("ATIVO");
        } else {
            txtSituacao.setText("EXCLUÍDO");
        }
    }

    private void LimpaTela(boolean LimpaTudo, boolean NovoRegistro) {

        txtCampoPesquisa.setText("");
        txtId_Prova.setText("");
        txtNome_Cliente.setText("");
        txtTelefone_Cliente.setText("");
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        formatador.format(data);
        txtData_Criacao.setText(formatador.format(data));
        System.out.println("Data Criacao:" + txtData_Criacao.getText());
        txtUsuario_Criacao.setText(Tela_Login.objMenu.mLoginUsuario);
        btConfirmar.setEnabled(vSelecao);
        btCancela.setEnabled(vSelecao);

        if (LimpaTudo == true){
            AtualizaClientes();
            jpManutencao.setEnabled(false);
            tbpClientes.setSelectedIndex(0);
            txtCampoPesquisa.requestFocus();
            btNovo.setVisible(true);
            btAdicionar.setVisible(false);
            btAlterar.setVisible(false);
            btExcluir.setVisible(false);
        }
        if (NovoRegistro == true){
            tbpClientes.setSelectedIndex(1);
            txtNome_Cliente.requestFocus();
            btNovo.setVisible(false);
            btAdicionar.setVisible(true);
            btAlterar.setVisible(false);
            btExcluir.setVisible(false);
            jpManutencao.setEnabled(true);
        }
    
   }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btExcluir1;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btNovo1;
    private javax.swing.JButton btNovo2;
    private javax.swing.JButton btPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JComboBox cbPesquisarPor;
    private javax.swing.JTable dtgClientes;
    private javax.swing.JTable dtgResultados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpManutencao;
    private javax.swing.JLabel lblLista;
    private javax.swing.JLabel lblLista1;
    private javax.swing.JLabel lblLista2;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLayeredPane pnlConsulta;
    private javax.swing.JLayeredPane pnlManutencao;
    private javax.swing.JRadioButton rbComecandoPor;
    private javax.swing.JRadioButton rbContendo;
    private javax.swing.JTabbedPane tbpClientes;
    private javax.swing.JTextField txtCampoPesquisa;
    private javax.swing.JFormattedTextField txtData_Criacao;
    private javax.swing.JTextField txtEndereco_Cliente;
    private javax.swing.JTextField txtId_Prova;
    private javax.swing.JTextField txtNome_Cliente;
    // End of variables declaration//GEN-END:variables

}
