/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.

 * Equipes.java
 *
 * Created on 13/03/2011, 18:46:50
 */
package Interface;

import Controle.Controla_Avaliacoes;
import Controle.Controla_Avaliacoes_Equipe;
import Modelo.Equipes;
import Modelo.ConexaoBD;
import Controle.Controla_Equipes;
import Ferramentas.CaixaDeDialogo;
import Ferramentas.Cronometro;
import Ferramentas.DLLInterface;
import Ferramentas.Entrada;
import Ferramentas.Formatacao;
import Modelo.Avaliacoes;
import Modelo.Avaliacoes_Equipe;
import java.awt.Color;
import java.awt.EventQueue;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JFormattedTextField;

/**
 *
 * @author Jonas
 */
public class Tela_Avaliacoes extends javax.swing.JFrame {

    Menu objMenu;
    DLLInterface dllInterface;
    public static Connection con;
    public static Statement stmt;
    public boolean vSelecao = true;
    //Equipes objEquipe = null;
    Controla_Equipes ctlEquipe;
    Equipes Equipes = new Equipes();
    double wPesoValidado;
    
    Controla_Avaliacoes ctlAvaliacoes;
    Avaliacoes avaliacoes = new Avaliacoes();

    Controla_Avaliacoes_Equipe ctlAvaliacoes_Equipe;
    Avaliacoes_Equipe avaliacao_Equipe = new Avaliacoes_Equipe();

    private JFormattedTextField txtTelefone_Equipe;
    private JFormattedTextField txtTelefone_Cliente;

    /**
     * Creates new form Equipes
     */
    public Tela_Avaliacoes(String pPesquisa) {
        abreConexao();
        this.setLocation(20, 100);
        initComponents();

        ButtonGroup bg = new ButtonGroup();
        bg.add(rbComecandoPor); // jRadioButton1
        bg.add(rbContendo); // jRadioButton2

        LimpaTela(true, false);
        txtCampoPesquisa.setText(pPesquisa);

        System.out.print("pPesquisa = " + pPesquisa);
        cbPesquisarPor.setSelectedItem("Nome_Equipe");
        btPesquisarActionPerformed(null);

    }

//    public Equipes(Equipes objEquipe) {
//        this.objEquipe = objEquipe;
//    }
    private void abreConexao() {
        try {
            con = ConexaoBD.getInstance().getConnection();
            stmt = con.createStatement();
            System.out.print("Conexão com Banco de Dados Criada!");
        } catch (Exception e) {
            System.out.print(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btAlterar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        txtPesoMaximoSimulado = new javax.swing.JTextField();
        lblPorta = new javax.swing.JLabel();
        txtPorta = new javax.swing.JTextField();
        cbSimulado = new javax.swing.JCheckBox();
        lblKG = new javax.swing.JLabel();
        cbBalanca = new javax.swing.JCheckBox();
        tbpAvaliacoes = new javax.swing.JTabbedPane();
        pnlConsulta = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        rbComecandoPor = new javax.swing.JRadioButton();
        rbContendo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtgAvaliacoes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbPesquisarPor = new javax.swing.JComboBox();
        txtCampoPesquisa = new javax.swing.JTextField();
        pnlManutencao = new javax.swing.JLayeredPane();
        jpManutencao = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dtgResultados = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId_Prova = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtData_Criacao = new javax.swing.JFormattedTextField();
        txtTelefone_Cliente = Formatacao.getTelefone();
        jLabel4 = new javax.swing.JLabel();
        txtId_Equipe = new javax.swing.JTextField();
        txtNome_Equipe = new javax.swing.JTextField();
        btPesquisarEquipe = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtLider_Equipe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPeso_Ponte = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btIniciaTimer = new javax.swing.JButton();
        lblTimer1 = new javax.swing.JLabel();
        lblAprovado = new javax.swing.JLabel();
        btProblema = new javax.swing.JButton();
        btExcluirEquipe = new javax.swing.JButton();
        txtPeso = new javax.swing.JTextField();
        btAdicionarEquipe = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblLista1 = new javax.swing.JLabel();
        lblLista2 = new javax.swing.JLabel();
        lblLista4 = new javax.swing.JLabel();
        lblLista3 = new javax.swing.JLabel();
        lblPosicaoAtual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Avaliações");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Lapis2.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setPreferredSize(new java.awt.Dimension(77, 25));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Novo.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setPreferredSize(new java.awt.Dimension(77, 25));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Porta.PNG"))); // NOI18N
        btFechar.setText("Fechar");
        btFechar.setPreferredSize(new java.awt.Dimension(77, 25));
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Mais.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Exclui.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setPreferredSize(new java.awt.Dimension(77, 25));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        txtPesoMaximoSimulado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblPorta.setText("PORTA");

        txtPorta.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        cbSimulado.setSelected(true);
        cbSimulado.setText("SIMULADO");
        cbSimulado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSimuladoItemStateChanged(evt);
            }
        });
        cbSimulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSimuladoActionPerformed(evt);
            }
        });

        lblKG.setText("KG");

        cbBalanca.setSelected(true);
        cbBalanca.setText("B");
        cbBalanca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbBalancaItemStateChanged(evt);
            }
        });
        cbBalanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBalancaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSimulado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblKG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesoMaximoSimulado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPorta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBalanca)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesoMaximoSimulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSimulado)
                    .addComponent(lblPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKG)
                    .addComponent(cbBalanca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 770, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        rbComecandoPor.setSelected(true);
        rbComecandoPor.setText("Começando Por");
        rbComecandoPor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbComecandoPorStateChanged(evt);
            }
        });

        rbContendo.setText("Contendo");
        rbContendo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbContendoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rbContendo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbComecandoPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbComecandoPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(rbContendo)
                .addContainerGap())
        );

        pnlConsulta.add(jPanel2);
        jPanel2.setBounds(360, 0, 410, 90);
        jPanel2.getAccessibleContext().setAccessibleName("Seleção");

        dtgAvaliacoes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dtgAvaliacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtgAvaliacoesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dtgAvaliacoesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(dtgAvaliacoes);

        pnlConsulta.add(jScrollPane1);
        jScrollPane1.setBounds(0, 90, 770, 310);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jLabel8.setText("Pesquisar Por");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(cbPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btPesquisar))
                    .addComponent(txtCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPesquisar))
                .addGap(6, 6, 6)
                .addComponent(txtCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlConsulta.add(jPanel3);
        jPanel3.setBounds(0, 0, 360, 90);

        tbpAvaliacoes.addTab("Consulta", pnlConsulta);

        pnlManutencao.setEnabled(false);

        jpManutencao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpManutencao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        dtgResultados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dtgResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtgResultadosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dtgResultadosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(dtgResultados);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );

        jpManutencao.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 340, 380));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        jPanel5.setLayout(null);

        jLabel2.setText("Id");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(10, 20, 30, 20);

        txtId_Prova.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId_Prova.setEnabled(false);
        jPanel5.add(txtId_Prova);
        txtId_Prova.setBounds(50, 20, 30, 20);

        jLabel5.setText("Data");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(110, 20, 32, 20);

        txtData_Criacao.setEditable(false);
        jPanel5.add(txtData_Criacao);
        txtData_Criacao.setBounds(140, 20, 102, 20);

        jLabel4.setText("Equipe");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(10, 50, 40, 20);

        txtId_Equipe.setEditable(false);
        txtId_Equipe.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel5.add(txtId_Equipe);
        txtId_Equipe.setBounds(50, 50, 30, 20);

        txtNome_Equipe.setEditable(false);
        txtNome_Equipe.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel5.add(txtNome_Equipe);
        txtNome_Equipe.setBounds(90, 50, 162, 20);

        btPesquisarEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lupa.png"))); // NOI18N
        btPesquisarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarEquipeActionPerformed(evt);
            }
        });
        jPanel5.add(btPesquisarEquipe);
        btPesquisarEquipe.setBounds(260, 50, 23, 25);

        jLabel6.setText("Peso da Ponte (Kg)");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(220, 80, 110, 20);

        txtLider_Equipe.setEditable(false);
        txtLider_Equipe.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel5.add(txtLider_Equipe);
        txtLider_Equipe.setBounds(50, 80, 162, 20);

        jLabel7.setText("Líder");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(10, 80, 40, 20);

        txtPeso_Ponte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(txtPeso_Ponte);
        txtPeso_Ponte.setBounds(340, 80, 50, 20);

        jpManutencao.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 110));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Prova"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btIniciaTimer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btIniciaTimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/timer.png"))); // NOI18N
        btIniciaTimer.setText("START");
        btIniciaTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciaTimerActionPerformed(evt);
            }
        });
        jPanel6.add(btIniciaTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 45));

        lblTimer1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTimer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimer1.setText("10");
        lblTimer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(lblTimer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 60, 40));

        lblAprovado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAprovado.setForeground(new java.awt.Color(0, 204, 0));
        lblAprovado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAprovado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblAprovadoFocusGained(evt);
            }
        });
        lblAprovado.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblAprovadoInputMethodTextChanged(evt);
            }
        });
        jPanel6.add(lblAprovado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 230, 50));

        btProblema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Exclui.png"))); // NOI18N
        btProblema.setText("Problema");
        btProblema.setPreferredSize(new java.awt.Dimension(77, 25));
        btProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProblemaActionPerformed(evt);
            }
        });
        jPanel6.add(btProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 120, -1));

        btExcluirEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Exclui.png"))); // NOI18N
        btExcluirEquipe.setText("Equipe");
        btExcluirEquipe.setPreferredSize(new java.awt.Dimension(77, 25));
        btExcluirEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirEquipeActionPerformed(evt);
            }
        });
        jPanel6.add(btExcluirEquipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 100, -1));

        txtPeso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 150, 40));

        btAdicionarEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Confirma.png"))); // NOI18N
        btAdicionarEquipe.setText("Adicionar");
        btAdicionarEquipe.setOpaque(false);
        btAdicionarEquipe.setPreferredSize(new java.awt.Dimension(77, 25));
        btAdicionarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarEquipeActionPerformed(evt);
            }
        });
        jPanel6.add(btAdicionarEquipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, -1));

        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lampred.png"))); // NOI18N
        jPanel6.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jpManutencao.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 400, 160));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Próximas Equipes"));
        jPanel7.setLayout(null);

        lblLista1.setText("1 - Equipe UNIVATES");
        jPanel7.add(lblLista1);
        lblLista1.setBounds(10, 20, 140, 20);

        lblLista2.setText("2 - Equipe MASSAFORTE");
        jPanel7.add(lblLista2);
        lblLista2.setBounds(10, 40, 140, 20);

        lblLista4.setText("4 - Equipe PONTE FORTE");
        jPanel7.add(lblLista4);
        lblLista4.setBounds(170, 40, 140, 20);

        lblLista3.setText("Equipe INOVA");
        jPanel7.add(lblLista3);
        lblLista3.setBounds(170, 20, 140, 20);

        jpManutencao.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 400, 70));

        lblPosicaoAtual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPosicaoAtual.setForeground(new java.awt.Color(51, 51, 255));
        lblPosicaoAtual.setText("PosiçãoAtual:");
        jpManutencao.add(lblPosicaoAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 390, -1));

        pnlManutencao.add(jpManutencao);
        jpManutencao.setBounds(0, 0, 770, 400);

        tbpAvaliacoes.addTab("Manutenção", pnlManutencao);

        getContentPane().add(tbpAvaliacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, 780, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int wControle = 0;

        wControle = Tela_Login.objMenu.preencheJanelas("Equipes", "I");
        if (wControle != 0) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Equipes'");
        }
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        int wControle = 0;
//
//        wControle = Tela_Login.objMenu.preencheJanelas("Equipes", "I");
//            if (wControle != 0){
//            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Equipes'");
//            }
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        int wControle = 0;

        wControle = Tela_Login.objMenu.preencheJanelas("Avaliacoes", "I");
        if (wControle != 0) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Avaliacoes'");
        }
        dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        int wControle = 0;
        String xMensagemValidacao = "";

        xMensagemValidacao = ValidaDados("");
        if (xMensagemValidacao.equals("")) {
            System.out.println("Validou Dados");

            Equipes.definirId_Equipe(Integer.parseInt(txtId_Prova.getText()));
        //Equipes.definirNome_Equipe(txtNome_Equipe.getText());
            //Equipes.definirTelefone(txtTelefone_Equipe.getText().replace("(","").replace(")","").replace("-",""));
            GuardaDados(false);
            System.out.println("Guardou Dados");

            wControle = ctlEquipe.alterarEquipe();
            if (wControle != 0) {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Equipe alterado com sucesso!");
                LimpaTela(true, false);
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao alterar cliente!");
            }
        } else {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erros de Validação: \n" + xMensagemValidacao);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        LimpaTela(true, false);
    }//GEN-LAST:event_btLimparActionPerformed

    private void dtgAvaliacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgAvaliacoesMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_dtgAvaliacoesMouseClicked

    private void dtgAvaliacoesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgAvaliacoesMousePressed
        // TODO add your handling code here:
        int wControle;
        int linhaSelecionada = dtgAvaliacoes.getSelectedRow();//pega a linha selecionada
        String coluna1 = dtgAvaliacoes.getModel().getValueAt(linhaSelecionada, 0).toString(); // Primeira coluna da linha

        if (dtgAvaliacoes.isColumnSelected(2)) {
            tbpAvaliacoes.setSelectedIndex(1);
            txtNome_Equipe.requestFocus();
            btAlterar.setVisible(true);
            //btExcluir.setVisible(true);
            //btNovo.setVisible(true);
            btAdicionarEquipe.setVisible(false);

            ctlAvaliacoes = new Controla_Avaliacoes(avaliacoes, dtgAvaliacoes);

            avaliacoes.definirId_Avaliacao(Integer.parseInt(coluna1));
            wControle = ctlAvaliacoes.buscarAvaliacao();
            if (wControle < 0) {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao buscar Prova no BD!");
            } else {
                if (wControle == 0) {
                    TelaAlteracao();
                }
                //AtualizaAvaliacoesEquipes();
            }
        }
    }//GEN-LAST:event_dtgAvaliacoesMousePressed

    private void AdicionarEquipe(boolean pAprovado, String pProblema) {
        try {
            int wControle = 0;
            String xMensagemValidacao = "";

            xMensagemValidacao = ValidaDados(pProblema);
            if (xMensagemValidacao.equals("")) {
                System.out.println("Validou Dados");
                GuardaDadosAvaliacaoEquipe(pAprovado, pProblema);
                System.out.println("Guardou Dados");

                wControle = ctlAvaliacoes_Equipe.gravarAvaliacao_Equipe();
                if (wControle != 0) {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Avaliação gravada com sucesso!");
                    LimpaTela(false, false);
                } else {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao gravar Avaliação!");
                }
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erros de Validação: \n" + xMensagemValidacao);
            }

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Ocorreu um erro: \n" + ex.getMessage().toString());
        }
    }

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int wControle = 0;

        char wChar = 'p';
        boolean wPergunta = false;

        wPergunta = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Tem certeza de que deseja excluir a Avaliação?", "", wChar);

        if (wPergunta == true) {
            Equipes.definirId_Equipe(Integer.parseInt(txtId_Prova.getText()));
            Equipes.definirUsuario_Exclusao(Tela_Login.objMenu.mIdUsuarioLogin);
            Date data = new Date();
            SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
            formatador.format(data);
            Equipes.definirData_Exclusao(formatador.format(data));
            wControle = ctlEquipe.excluirEquipe();
            if (wControle != 0) {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Equipe excluído com sucesso!");
                LimpaTela(true, false);
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao excluir cliente!");
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        String pTipoSelecao = "";
        if (rbComecandoPor.isSelected()) {
            pTipoSelecao = "CP";
        } else {
            pTipoSelecao = "CT";
        }

        ctlAvaliacoes.PreencheAvaliacoes(cbPesquisarPor.getSelectedItem().toString(), txtCampoPesquisa.getText(), pTipoSelecao);
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void rbComecandoPorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbComecandoPorStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_rbComecandoPorStateChanged

    private void rbContendoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbContendoStateChanged
        // TODO add your handling code here:
        //rbComecandoPor.setSelected(false);
        //rbContendo.setSelected(true);
    }//GEN-LAST:event_rbContendoStateChanged

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        int wControle;

        try {

            LimpaTela(true, true);

            GuardaDados(true);
            System.out.println("Guardou Dados");

            wControle = ctlAvaliacoes.gravarAvaliacao();
            if (wControle != 0) {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Avaliação gravada com sucesso!");

                avaliacoes.definirId_Avaliacao(wControle);
                wControle = ctlAvaliacoes.buscarAvaliacao();
                if (wControle < 0) {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao buscar Avaliação no BD!");
                } else {
                    if (wControle == 0) {
                        TelaAlteracao();
                    }
                }

            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao gravar Avaliação!");
            }

        } catch (Exception ex) {

        }

    }//GEN-LAST:event_btNovoActionPerformed

    private void dtgResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgResultadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dtgResultadosMouseClicked

    private void dtgResultadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgResultadosMousePressed
        int wControle;
        int linhaSelecionada = dtgResultados.getSelectedRow();//pega a linha selecionada
        String coluna1 = dtgResultados.getModel().getValueAt(linhaSelecionada, 0).toString(); // Primeira coluna da linha
        //String coluna2 = dtgResultados.getModel().getValueAt(linhaSelecionada, 1).toString(); // SEgunda coluna da linha

        if (dtgResultados.isColumnSelected(3)) {
            //tbpAvaliacoes.setSelectedIndex(1);
            //txtNome_Equipe.requestFocus();
            //btAlterar.setVisible(true);
            btExcluirEquipe.setVisible(true);
            //btNovo.setVisible(true);
            btAdicionarEquipe.setVisible(false);

            ctlAvaliacoes_Equipe = new Controla_Avaliacoes_Equipe(avaliacao_Equipe, dtgResultados);

            avaliacao_Equipe.definirId_Avaliacao(Integer.parseInt(txtId_Prova.getText()));
            avaliacao_Equipe.definirId_Equipe(Integer.parseInt(coluna1));
            wControle = ctlAvaliacoes_Equipe.buscarAvaliacao_Equipe();
            if (wControle < 0) {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao buscar Prova no BD!");
            } else {
                if (wControle == 0) {
                    txtId_Equipe.setText(Integer.toString(avaliacao_Equipe.obterId_Equipe()));
                }
                txtId_Prova.setText(Integer.toString(avaliacao_Equipe.obterId_Avaliacao()));
                txtNome_Equipe.setText(avaliacao_Equipe.obterNome_Equipe());
                txtPesoMaximoSimulado.setText(Double.toString(avaliacao_Equipe.obterPeso_Ponte()));
            }
        }
    }//GEN-LAST:event_dtgResultadosMousePressed

    public void capturaPeso() {
        double wPeso;
        int wControle;
        try {
            lblStatus.setVisible(false);
            lblAprovado.setText("");

            if (cbSimulado.isSelected() == false) {
                int wPorta = Integer.parseInt(txtPorta.getText());
                wPeso = dllInterface.BalancaLider.CapturarPeso(wPorta, 9600);
                //BigDecimal valorExato = new BigDecimal(wPeso)  
                // .setScale(2, RoundingMode.HALF_DOWN);  
                //double teste = dllInterface.BalancaLider.Zerar(wPorta, 9600);
            } else {
                Random random = new Random();
                wPeso = random.nextInt(Integer.parseInt(txtPesoMaximoSimulado.getText()));

            }

            if (txtPeso.getText().equals("")){
                txtPeso.setOpaque(false);
                    txtPeso.setText(wPeso + "");
                    //lblPesoSuportado.setText("%.2f",wPeso);
                    //lblPesoSuportado.setText(wPeso);
                    lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lampgreen.png")));
                    lblStatus.setVisible(true);
                    lblAprovado.setText("PESO APROVADO!");

                    wControle = ctlAvaliacoes_Equipe.buscarPosicaoAvaliacao_Equipe(Double.parseDouble(txtPeso.getText()), Double.parseDouble(txtPeso_Ponte.getText()));
                    if (wControle != 0) {
                        lblPosicaoAtual.setText("No momento a equipe ocupa a " + wControle + "ª posição!");
                    }
            }else{
                if (wPeso >= Double.parseDouble(txtPeso.getText())) {
                    txtPeso.setOpaque(false);
                    txtPeso.setText(wPeso + "");
                    //lblPesoSuportado.setText("%.2f",wPeso);
                    //lblPesoSuportado.setText(wPeso);
                    lblAprovado.setForeground(Color.GREEN);
                    lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lampgreen.png")));
                    lblStatus.setVisible(true);
                    lblAprovado.setText("PESO APROVADO!");

                    wControle = ctlAvaliacoes_Equipe.buscarPosicaoAvaliacao_Equipe(Double.parseDouble(txtPeso.getText()), Double.parseDouble(txtPeso_Ponte.getText()));
                    if (wControle != 0) {
                        lblPosicaoAtual.setText("No momento a equipe ocupa a " + wControle + "ª posição!");
                    }
                } else {
                    lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lampred.png")));
                    lblStatus.setVisible(true);
                    lblAprovado.setForeground(Color.RED);
                    lblAprovado.setText("PONTE QUEBRADA!");

                    //salva o resultado
                    GuardaDadosAvaliacaoEquipe(true, "");
                    wControle = ctlAvaliacoes_Equipe.gravarAvaliacao_Equipe();

                    AtualizaAvaliacoesEquipes();
                    LimpaTela(false, true);
                }
            }

            if (cbSimulado.isSelected() == false) {
                //wPeso = dllInterface.BalancaLider.Zerar(Integer.parseInt(txtPorta.getText()), 9600);
                //wControle2 = Integer.parseInt(DLLInterface.BalancaLider.CapturarPeso(4, 9600) + "");
                //wControle = DLLInterface.BalancaLider.CapturarPeso(Integer.parseInt(txtPorta.getText()), Integer.parseInt(txtVelocidade.getText()));
            }

        } catch (Exception ex) {
            System.out.println("ERRO NO BOTÃO TIMER: " + ex.getMessage());
        }

    }
    private void btIniciaTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciaTimerActionPerformed
        try{
            lblStatus.setVisible(false);
            lblAprovado.setText("");
        if (cbSimulado.isSelected() == true) {
            if (txtPeso_Ponte.getText().equals("")){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Informe o peso da ponte de espaguete da Equipe!");
            }
            Cronometro crono = new Cronometro(lblTimer1, 10, this, btIniciaTimer);
            crono.start();
            
            
        } else if (!txtPorta.getText().equals("")) {
            Cronometro crono = new Cronometro(lblTimer1, 10, this, btIniciaTimer);
            crono.start();
            
            /*crono.join();
            while (! crono.wEspera){
                this.repaint();
            }
            capturaPeso();
            */
            
        } else {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Informe a Porta de Comunicação da Balança!");
        }
        
        }catch(Exception e){
        }
    }//GEN-LAST:event_btIniciaTimerActionPerformed

    private void btProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProblemaActionPerformed
        try{
            String wProblema = "";
            while(wProblema.trim().equals("")){
                wProblema = Entrada.leiaString("Informe o Problema Ocorrido");
            }
                    
            if (! wProblema.trim().equals("")){
                AdicionarEquipe(false, wProblema);
                AtualizaAvaliacoesEquipes(); 
            }
        }catch(Exception ex){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage().toString()); 
        }
    }//GEN-LAST:event_btProblemaActionPerformed

    private void btPesquisarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarEquipeActionPerformed
        Tela_Equipes objEquipes;
        objEquipes = new Tela_Equipes(txtNome_Equipe.getText());
        objEquipes.vSelecao = true;
        objEquipes.btCancela.setEnabled(true);
        objEquipes.btConfirmar.setEnabled(true);
        objEquipes.setVisible(true);
    }//GEN-LAST:event_btPesquisarEquipeActionPerformed

    private void cbSimuladoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSimuladoItemStateChanged
        // TODO add your handling code here:
        if (cbSimulado.isSelected()) {
            lblPorta.setVisible(false);
            txtPorta.setVisible(false);
            lblKG.setVisible(true);
            txtPesoMaximoSimulado.setVisible(true);
        } else {
            lblPorta.setVisible(true);
            txtPorta.setVisible(true);
            lblKG.setVisible(false);
            txtPesoMaximoSimulado.setVisible(false);
        }
    }//GEN-LAST:event_cbSimuladoItemStateChanged

    private void btExcluirEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirEquipeActionPerformed

    private void lblAprovadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblAprovadoFocusGained
        if (cbBalanca.isSelected()){
            capturaPeso();
        } else{
            
        }        
    }//GEN-LAST:event_lblAprovadoFocusGained

    private void lblAprovadoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblAprovadoInputMethodTextChanged
  
    }//GEN-LAST:event_lblAprovadoInputMethodTextChanged

    private void cbSimuladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSimuladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSimuladoActionPerformed

    private void cbBalancaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbBalancaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBalancaItemStateChanged

    private void cbBalancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBalancaActionPerformed
        if (cbBalanca.isSelected()){
            txtPeso.setEnabled(false);
        }else{
            txtPeso.setEnabled(true);
        }
    }//GEN-LAST:event_cbBalancaActionPerformed

    private void btAdicionarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarEquipeActionPerformed
        AdicionarEquipe(true, "");
        AtualizaAvaliacoesEquipes();
    }//GEN-LAST:event_btAdicionarEquipeActionPerformed

    public static void RecebeEquipe(String Cod_Equipe, String Nome_Equipe, String Lider_Equipe) {
        txtId_Equipe.setText(Cod_Equipe);
        txtNome_Equipe.setText(Nome_Equipe);
        //txtLider_Equipe.setText(Lider_Equipe);
        //txtTelefone_Cliente.setText(Participantes_Equipe);
    }

    private void AtualizaAvaliacoes() {
        //objEquipes.setNome(txNomeMotorista.getText());
        //objEquipes.definirNome_Equipe('teste');
        //objEquipes.definirTelefone('teste');
        //objEquipes.setCategoriaCarteira('teste');
        ctlAvaliacoes = new Controla_Avaliacoes(avaliacoes, dtgAvaliacoes);

        //wControle = objEquipes_Implem.buscaEquipes();
        ctlAvaliacoes.PreencheAvaliacoes("", "", "");
        PreencheComboPesquisa();
    }

    private void Cronometro() {
        int tempo = 10;
        try {

            while (true) {
                EventQueue.invokeLater(new Runnable() {
                    public void run() {
                    }
                });
                Thread.sleep(1000);
                tempo = tempo - 1;
                lblTimer1.setText(tempo + "");

                if (tempo == 0) {
                    break;
                }
            }
        } catch (InterruptedException e) {
        }
    }

    private void AtualizaAvaliacoesEquipes() {
        //objEquipes.setNome(txNomeMotorista.getText());
        //objEquipes.definirNome_Equipe('teste');
        //objEquipes.definirTelefone('teste');
        //objEquipes.setCategoriaCarteira('teste');
        avaliacao_Equipe.definirId_Avaliacao(avaliacoes.obterId_Avaliacao());
        ctlAvaliacoes_Equipe = new Controla_Avaliacoes_Equipe(avaliacao_Equipe, dtgResultados);

        //wControle = objEquipes_Implem.buscaEquipes();
        ctlAvaliacoes_Equipe.PreencheAvaliacoes_Equipe(avaliacoes.obterId_Avaliacao());
        //PreencheComboPesquisa();
    }

    private void PreencheComboPesquisa() {

        cbPesquisarPor.removeAllItems();
        if ((dtgAvaliacoes.getColumnCount() - 1) > 0) {
            for (int i = 0; i < dtgAvaliacoes.getColumnCount() - 1; i++) {
                cbPesquisarPor.addItem(dtgAvaliacoes.getColumnName(i));
            }
        }

    }

    private String ValidaDados(String pProblema) {
        String xMensagem = "";

        if (txtNome_Equipe.getText().equals("")) {
            xMensagem += "Nome Equipe deve ser preenchido! \n";
        }

        if (pProblema.equals("")){
            if (txtPeso_Ponte.getText().equals("")) {
                xMensagem += "Peso da Ponte em Kg deve ser preenchido! \n";
            }   
        }

        return xMensagem;
    }

    private void GuardaDados(boolean RegistroNovo) {

        if (RegistroNovo == true) {
            System.out.println("Guardou Dados Registro Novo = true");
            avaliacoes.definirId_Avaliacao(0);
            avaliacoes.definirData_Criacao(txtData_Criacao.getText());
            avaliacoes.definirData_Avaliacao(txtData_Criacao.getText());
            avaliacoes.definirUsuario_Criacao(Tela_Login.objMenu.mIdUsuarioLogin);
            System.out.println("definirData_Criacao = " + txtData_Criacao.getText());
        } else {
            //A PRINCIPIO NAO PODE ALTERAR UMA PROVA
        }
    }

    private void GuardaDadosAvaliacaoEquipe(boolean pAprovado, String pProblema) {

        if (pAprovado == true) {
            avaliacao_Equipe.definirId_Equipe(Integer.parseInt(txtId_Equipe.getText()));
            avaliacao_Equipe.definirId_Avaliacao(Integer.parseInt(txtId_Prova.getText()));
            avaliacao_Equipe.definirPeso_Ponte(Double.parseDouble(txtPeso_Ponte.getText()));
            avaliacao_Equipe.definirPontuacao(Double.parseDouble(txtPeso.getText()));
            avaliacao_Equipe.definirProblema("");

            Date data = new Date();
            SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
            formatador.format(data);
            avaliacao_Equipe.definirData_Criacao(formatador.format(data));

            //avaliacao_Equipe.definirData_Criacao(txtData_Criacao.getText());
            avaliacao_Equipe.definirUsuario_Criacao(Tela_Login.objMenu.mIdUsuarioLogin);
            avaliacao_Equipe.definirAprovado(1); //APROVADO

        } else {
            avaliacao_Equipe.definirId_Equipe(Integer.parseInt(txtId_Equipe.getText()));
            avaliacao_Equipe.definirId_Avaliacao(Integer.parseInt(txtId_Prova.getText()));
            avaliacao_Equipe.definirPeso_Ponte(Double.parseDouble(txtPeso_Ponte.getText()));
            avaliacao_Equipe.definirPontuacao(0);
            avaliacao_Equipe.definirProblema(pProblema);

            //if (lblAprovado.getText().equals("PESO APROVADO")){
            //    avaliacao_Equipe.definirAprovado(1);
            //}else{
            avaliacao_Equipe.definirAprovado(0); //NÃO APROVADO
            //}
        }

    }

    private void TelaAlteracao() {

        pnlManutencao.setEnabled(true);
        tbpAvaliacoes.setSelectedIndex(1);
        txtId_Prova.setText(Integer.toString(avaliacoes.obterId_Avaliacao()));
        txtData_Criacao.setText(avaliacoes.obterData_Avaliacao());
        btAdicionarEquipe.setVisible(true);
        btExcluir.setVisible(true);
        btNovo.setVisible(false);
        //String data = Formatacao.ajustaDataDMA(Equipes.obterData_Criacao());
        //txtData_Criacao.setText(data);

        AtualizaAvaliacoesEquipes();

    }

    private void LimpaTela(boolean LimpaTudo, boolean NovoRegistro) {

        //lblStatus.setVisible(false);
        txtCampoPesquisa.setText("");
        txtId_Prova.setText("");
        txtId_Equipe.setText("");
        txtNome_Equipe.setText("");
        txtPesoMaximoSimulado.setText("");
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        formatador.format(data);
        txtData_Criacao.setText(formatador.format(data));
        System.out.println("Data Criacao:" + txtData_Criacao.getText());
        btAdicionarEquipe.setVisible(true);
        btExcluirEquipe.setVisible(false);

        if (cbSimulado.isSelected()) {
            lblPorta.setVisible(false);
            txtPorta.setVisible(false);
            lblKG.setVisible(true);
            txtPesoMaximoSimulado.setVisible(true);
        } else {
            lblPorta.setVisible(true);
            txtPorta.setVisible(true);
            lblKG.setVisible(false);
            txtPesoMaximoSimulado.setVisible(false);
        }
        
        if (cbBalanca.isSelected()) {
            txtPeso.setEnabled(false);
            btAdicionarEquipe.setVisible(false);
        } else {
            txtPeso.setEnabled(true);
            btAdicionarEquipe.setVisible(true);
        }

        if (LimpaTudo == true) {
            AtualizaAvaliacoes();
            jpManutencao.setEnabled(false);
            tbpAvaliacoes.setSelectedIndex(0);
            txtCampoPesquisa.requestFocus();
            btNovo.setVisible(true);
            //btAdicionar.setVisible(false);
            btAlterar.setVisible(false);
            btExcluir.setVisible(false);
        } else {
            tbpAvaliacoes.setSelectedIndex(1);
            txtNome_Equipe.requestFocus();
        }
        if (NovoRegistro == true) {
            tbpAvaliacoes.setSelectedIndex(1);
            txtNome_Equipe.requestFocus();
            btNovo.setVisible(false);
            btAlterar.setVisible(false);
            btExcluir.setVisible(false);
            jpManutencao.setEnabled(true);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Avaliacoes("").setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarEquipe;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btExcluirEquipe;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btIniciaTimer;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btPesquisarEquipe;
    private javax.swing.JButton btProblema;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbBalanca;
    private static javax.swing.JComboBox cbPesquisarPor;
    private javax.swing.JCheckBox cbSimulado;
    private javax.swing.JTable dtgAvaliacoes;
    private javax.swing.JTable dtgResultados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpManutencao;
    public javax.swing.JLabel lblAprovado;
    private javax.swing.JLabel lblKG;
    private javax.swing.JLabel lblLista1;
    private javax.swing.JLabel lblLista2;
    private javax.swing.JLabel lblLista3;
    private javax.swing.JLabel lblLista4;
    private javax.swing.JLabel lblPorta;
    private javax.swing.JLabel lblPosicaoAtual;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTimer1;
    private javax.swing.JLayeredPane pnlConsulta;
    private javax.swing.JLayeredPane pnlManutencao;
    private javax.swing.JRadioButton rbComecandoPor;
    private javax.swing.JRadioButton rbContendo;
    private javax.swing.JTabbedPane tbpAvaliacoes;
    private javax.swing.JTextField txtCampoPesquisa;
    private javax.swing.JFormattedTextField txtData_Criacao;
    private static javax.swing.JTextField txtId_Equipe;
    private javax.swing.JTextField txtId_Prova;
    private static javax.swing.JTextField txtLider_Equipe;
    private static javax.swing.JTextField txtNome_Equipe;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPesoMaximoSimulado;
    private javax.swing.JTextField txtPeso_Ponte;
    private javax.swing.JTextField txtPorta;
    // End of variables declaration//GEN-END:variables

}
