/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Equipes.java
 *
 * Created on 13/03/2011, 18:46:50
 */

package Interface;

import Modelo.Equipes;
import Modelo.ConexaoBD;
import Controle.Controla_Equipes;
import Ferramentas.CaixaDeDialogo;
import Ferramentas.Formatacao;
import Ferramentas.Validacao;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;

/**
 *
 * @author Jonas
 */
public class Tela_Equipes extends javax.swing.JFrame {
     Menu objMenu;
     public static Connection con;
     public static Statement stmt;
     public boolean vSelecao = true;
     //Equipes objEquipe = null;
     Controla_Equipes ctlEquipe;
     Equipes Equipes = new Equipes();
          
    /** Creates new form Equipes */
    public Tela_Equipes(String pPesquisa) {
        abreConexao();
        this.setLocation(20, 100);
        initComponents();

        ButtonGroup bg= new ButtonGroup();
        bg.add(rbComecandoPor); // jRadioButton1
        bg.add(rbContendo); // jRadioButton2

        LimpaTela(true,false);
        txtCampoPesquisa.setText(pPesquisa);
        if (!"".equals(pPesquisa)){
        System.out.print("pPesquisa = " + pPesquisa);
        cbPesquisarPor.setSelectedItem("Nome_Equipe");
        btPesquisarActionPerformed(null);
        } else {
         btCancela.setEnabled(false);
         btConfirmar.setEnabled(false);
        }

    }

//    public Equipes(Equipes objEquipe) {
//        this.objEquipe = objEquipe;
//    }


    private void abreConexao() {
        try {
        con = ConexaoBD.getInstance().getConnection();
        stmt = con.createStatement();
        System.out.print("Conexão com Banco de Dados Criada!");
        } catch (Exception e) {
        System.out.print(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        tbpEquipes = new javax.swing.JTabbedPane();
        pnlConsulta = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        rbComecandoPor = new javax.swing.JRadioButton();
        rbContendo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtgEquipes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbPesquisarPor = new javax.swing.JComboBox();
        txtCampoPesquisa = new javax.swing.JTextField();
        pnlManutencao = new javax.swing.JLayeredPane();
        jpManutencao = new javax.swing.JPanel();
        txtId_Equipe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome_Equipe = new javax.swing.JTextField();
        txtTelefone_Equipe = new javax.swing.JFormattedTextField();
        txtTelefone_Equipe = Formatacao.getTelefone();
        jLabel5 = new javax.swing.JLabel();
        txtData_Criacao = new javax.swing.JFormattedTextField();
        txtTelefone_Equipe = Formatacao.getTelefone();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario_Criacao = new javax.swing.JFormattedTextField();
        txtTelefone_Equipe = Formatacao.getTelefone();
        jLabel7 = new javax.swing.JLabel();
        txtSituacao = new javax.swing.JFormattedTextField();
        txtTelefone_Equipe = Formatacao.getTelefone();
        jLabel9 = new javax.swing.JLabel();
        txtEndereco_Equipe = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBairro_Equipe = new javax.swing.JTextField();
        btConfirmar = new javax.swing.JButton();
        btCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Equipes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Confirma.png"))); // NOI18N
        btAdicionar.setText("Adicionar");
        btAdicionar.setPreferredSize(new java.awt.Dimension(77, 25));
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Lapis2.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setPreferredSize(new java.awt.Dimension(77, 25));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Novo.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setPreferredSize(new java.awt.Dimension(77, 25));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Porta.PNG"))); // NOI18N
        btFechar.setText("Fechar");
        btFechar.setPreferredSize(new java.awt.Dimension(77, 25));
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Exclui.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setPreferredSize(new java.awt.Dimension(77, 25));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Mais.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovo)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        rbComecandoPor.setSelected(true);
        rbComecandoPor.setText("Começando Por");
        rbComecandoPor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbComecandoPorStateChanged(evt);
            }
        });

        rbContendo.setText("Contendo");
        rbContendo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbContendoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rbContendo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbComecandoPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbComecandoPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(rbContendo)
                .addContainerGap())
        );

        pnlConsulta.add(jPanel2);
        jPanel2.setBounds(430, 0, 210, 90);
        jPanel2.getAccessibleContext().setAccessibleName("Seleção");

        dtgEquipes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dtgEquipes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtgEquipesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dtgEquipesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(dtgEquipes);

        pnlConsulta.add(jScrollPane1);
        jScrollPane1.setBounds(0, 90, 640, 280);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jLabel8.setText("Pesquisar Por");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPesquisar))
                    .addComponent(txtCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlConsulta.add(jPanel3);
        jPanel3.setBounds(0, 0, 430, 90);

        tbpEquipes.addTab("Consulta", pnlConsulta);

        pnlManutencao.setEnabled(false);

        jpManutencao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpManutencao.setLayout(null);

        txtId_Equipe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId_Equipe.setEnabled(false);
        jpManutencao.add(txtId_Equipe);
        txtId_Equipe.setBounds(190, 30, 60, 20);

        jLabel4.setText("Nome");
        jpManutencao.add(jLabel4);
        jLabel4.setBounds(80, 60, 80, 20);

        jLabel3.setText("Telefone");
        jpManutencao.add(jLabel3);
        jLabel3.setBounds(80, 150, 80, 20);

        jLabel2.setText("Id Cliente");
        jpManutencao.add(jLabel2);
        jLabel2.setBounds(80, 30, 80, 20);

        txtNome_Equipe.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jpManutencao.add(txtNome_Equipe);
        txtNome_Equipe.setBounds(190, 60, 210, 20);
        jpManutencao.add(txtTelefone_Equipe);
        txtTelefone_Equipe.setBounds(190, 150, 102, 20);

        jLabel5.setText("Data de Criação");
        jpManutencao.add(jLabel5);
        jLabel5.setBounds(80, 312, 100, 20);

        txtData_Criacao.setEditable(false);
        jpManutencao.add(txtData_Criacao);
        txtData_Criacao.setBounds(190, 310, 102, 20);

        jLabel6.setText("Usuário Criação");
        jpManutencao.add(jLabel6);
        jLabel6.setBounds(80, 338, 100, 20);

        txtUsuario_Criacao.setEditable(false);
        jpManutencao.add(txtUsuario_Criacao);
        txtUsuario_Criacao.setBounds(190, 340, 102, 20);

        jLabel7.setText("Situação");
        jpManutencao.add(jLabel7);
        jLabel7.setBounds(80, 180, 80, 20);

        txtSituacao.setEditable(false);
        jpManutencao.add(txtSituacao);
        txtSituacao.setBounds(190, 180, 102, 20);

        jLabel9.setText("Integrantes");
        jpManutencao.add(jLabel9);
        jLabel9.setBounds(80, 90, 80, 20);

        txtEndereco_Equipe.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jpManutencao.add(txtEndereco_Equipe);
        txtEndereco_Equipe.setBounds(190, 90, 210, 20);

        jLabel10.setText("Líder");
        jpManutencao.add(jLabel10);
        jLabel10.setBounds(80, 120, 80, 20);

        txtBairro_Equipe.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jpManutencao.add(txtBairro_Equipe);
        txtBairro_Equipe.setBounds(190, 120, 210, 20);

        btConfirmar.setText("Confirma");
        btConfirmar.setEnabled(false);
        btConfirmar.setPreferredSize(new java.awt.Dimension(77, 25));
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });
        jpManutencao.add(btConfirmar);
        btConfirmar.setBounds(444, 338, 90, 20);

        btCancela.setText("Cancela");
        btCancela.setEnabled(false);
        btCancela.setPreferredSize(new java.awt.Dimension(77, 25));
        btCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaActionPerformed(evt);
            }
        });
        jpManutencao.add(btCancela);
        btCancela.setBounds(540, 338, 90, 20);

        pnlManutencao.add(jpManutencao);
        jpManutencao.setBounds(0, 0, 640, 370);

        tbpEquipes.addTab("Manutenção", pnlManutencao);

        getContentPane().add(tbpEquipes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, 650, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int wControle = 0;

        wControle = Tela_Login.objMenu.preencheJanelas("Equipes", "I");
            if (wControle != 0){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Equipes'");
            }
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        int wControle = 0;
//
//        wControle = Tela_Login.objMenu.preencheJanelas("Equipes", "I");
//            if (wControle != 0){
//            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Equipes'");
//            }
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        int wControle = 0;

        wControle = Tela_Login.objMenu.preencheJanelas("Equipes", "I");
            if (wControle != 0){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Equipes'");
            }
        dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        int wControle = 0;
        String xMensagemValidacao = "";

        xMensagemValidacao = ValidaDados();
        if (xMensagemValidacao.equals("")){
        System.out.println("Validou Dados");

        Equipes.definirId_Equipe(Integer.parseInt(txtId_Equipe.getText()));
        //Equipes.definirNome_Equipe(txtNome_Equipe.getText());
        //Equipes.definirTelefone(txtTelefone_Equipe.getText().replace("(","").replace(")","").replace("-",""));
        GuardaDados(false);
        System.out.println("Guardou Dados");

        wControle = ctlEquipe.alterarEquipe();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Equipe alterada com sucesso!");
           LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao alterar equipe!");
           }
        } else {
        CaixaDeDialogo.obterinstancia().exibirMensagem("Erros de Validação: \n" + xMensagemValidacao);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        LimpaTela(true,false);
    }//GEN-LAST:event_btLimparActionPerformed

    private void dtgEquipesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgEquipesMouseClicked
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_dtgEquipesMouseClicked

    private void dtgEquipesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgEquipesMousePressed
        // TODO add your handling code here:
        int wControle;
        int linhaSelecionada = dtgEquipes.getSelectedRow();//pega a linha selecionada
        String coluna1 = dtgEquipes.getModel().getValueAt(linhaSelecionada, 0).toString(); // Primeira coluna da linha
        
        if (dtgEquipes.isColumnSelected(3)){
            tbpEquipes.setSelectedIndex(1);
            txtNome_Equipe.requestFocus();
            btAlterar.setVisible(true);
            btExcluir.setVisible(true);
            btNovo.setVisible(false);
            btAdicionar.setVisible(true);

            ctlEquipe = new Controla_Equipes(Equipes, dtgEquipes);

            Equipes.definirId_Equipe(Integer.parseInt(coluna1));
            wControle = ctlEquipe.buscarEquipe();
                if (wControle < 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao buscar Equipe no BD!");
                } else {
                if (wControle == 0)
                    TelaAlteracao();
                }
     }
    }//GEN-LAST:event_dtgEquipesMousePressed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        Tela_Avaliacoes.RecebeEquipe(txtId_Equipe.getText(), txtNome_Equipe.getText(), txtBairro_Equipe.getText());
        dispose();
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaActionPerformed
        // TODO add your handling code here:
        Tela_Avaliacoes.RecebeEquipe("","","");
        dispose();
    }//GEN-LAST:event_btCancelaActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        LimpaTela(true,true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        int wControle = 0;
        String xMensagemValidacao = "";
        
        xMensagemValidacao = ValidaDados();
        if (xMensagemValidacao.equals("")){
        System.out.println("Validou Dados");
        GuardaDados(true);
        System.out.println("Guardou Dados");

        wControle = ctlEquipe.gravarEquipe();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Equipe gravada com sucesso!");
            LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao gravar equipe!");
           }
        } else {
        CaixaDeDialogo.obterinstancia().exibirMensagem("Erros de Validação: \n" + xMensagemValidacao);
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int wControle = 0;

        char wChar = 'p';
        boolean wPergunta = false;

        wPergunta = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Tem certeza de que deseja excluir a Equipe?","",wChar);

        if (wPergunta == true){
        Equipes.definirId_Equipe(Integer.parseInt(txtId_Equipe.getText()));
        Equipes.definirUsuario_Exclusao(Tela_Login.objMenu.mIdUsuarioLogin);
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        formatador.format(data);
        Equipes.definirData_Exclusao(formatador.format(data));
        wControle = ctlEquipe.excluirEquipe();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Equipe excluída com sucesso!");
           LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao excluir equipe!");
          }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        String pTipoSelecao = "";
        if (rbComecandoPor.isSelected()){
           pTipoSelecao = "CP";
        } else {
           pTipoSelecao = "CT";
        }

        ctlEquipe.PreencheEquipes(cbPesquisarPor.getSelectedItem().toString(),txtCampoPesquisa.getText(), pTipoSelecao);
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void rbComecandoPorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbComecandoPorStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbComecandoPorStateChanged

    private void rbContendoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbContendoStateChanged
        // TODO add your handling code here:
        //rbComecandoPor.setSelected(false);
        //rbContendo.setSelected(true);
    }//GEN-LAST:event_rbContendoStateChanged

    private void AtualizaEquipes(){
        //objEquipes.setNome(txNomeMotorista.getText());
        //objEquipes.definirNome_Equipe('teste');
        //objEquipes.definirTelefone('teste');
        //objEquipes.setCategoriaCarteira('teste');
        ctlEquipe = new Controla_Equipes(Equipes, dtgEquipes);
        
        //wControle = objEquipes_Implem.buscaEquipes();
        ctlEquipe.PreencheEquipes("","","");
        PreencheComboPesquisa();
    }

        private void PreencheComboPesquisa(){

        cbPesquisarPor.removeAllItems();
        if ((dtgEquipes.getColumnCount() - 1) > 0){
            for (int i= 0; i < dtgEquipes.getColumnCount() - 1; i++){
              cbPesquisarPor.addItem(dtgEquipes.getColumnName(i));
            }
        }
        
    }

        private String ValidaDados() {
        String xMensagem = "";
        
        if(txtNome_Equipe.getText().equals("")){
        xMensagem +="Nome Equipe deve ser preenchido! \n";
        }

        if (txtTelefone_Equipe.getText().replace("(", "").replace(")","").replace("-","").replace(" ","").length() > 0){
        Validacao.validarTelefone(txtTelefone_Equipe);
            if (txtTelefone_Equipe.getText().replace("(", "").replace(")","").replace("-","").replace(" ","").length() == 0){
            xMensagem +="Telefone Equipe deve ser preenchido corretamente! \n";
            }
        }
        return xMensagem;
     }

        private void GuardaDados(boolean RegistroNovo) {

        if (RegistroNovo == true){
        System.out.println("Guardou Dados Registro Novo = true");
        Equipes.definirId_Equipe(0);
        Equipes.definirNome_Equipe(txtNome_Equipe.getText());
        Equipes.definirTelefone(txtTelefone_Equipe.getText().replace("(","").replace(")","").replace("-",""));
        Equipes.definirUsuario_Criacao(Tela_Login.objMenu.mIdUsuarioLogin);
        Equipes.definirData_Criacao(txtData_Criacao.getText());
        System.out.println("definirData_Criacao = " + txtData_Criacao.getText());
        //ctlEquipe = new Controla_Equipes(Equipes, dtgEquipes);
        } else {
        System.out.println("Guardou Dados Registro Novo = false");
        Equipes.definirNome_Equipe(txtNome_Equipe.getText());
        Equipes.definirTelefone(txtTelefone_Equipe.getText().replace("(","").replace(")","").replace("-",""));
        }
    }

    private void TelaAlteracao() {

        try{
        
            pnlManutencao.setEnabled(true);
            txtId_Equipe.setText(Integer.toString(Equipes.obterId_Equipe()));
            txtNome_Equipe.setText(Equipes.obterNome_Equipe());
            txtTelefone_Equipe.setText(Equipes.obterTelefone());

            //String data = Formatacao.ajustaDataDMA(Equipes.obterData_Criacao());
            txtData_Criacao.setText(Equipes.obterData_Criacao());

            if (Equipes.obterData_Exclusao() == null){
                txtSituacao.setText("ATIVO");
            } else {
                txtSituacao.setText("EXCLUÍDO");
            }
        
        }catch(Exception ex){
            
        }
    }

    private void LimpaTela(boolean LimpaTudo, boolean NovoRegistro) {

        txtCampoPesquisa.setText("");
        txtId_Equipe.setText("");
        txtNome_Equipe.setText("");
        txtTelefone_Equipe.setText("");
        txtBairro_Equipe.setText("");
        txtEndereco_Equipe.setText("");
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        formatador.format(data);
        txtData_Criacao.setText(formatador.format(data));
        System.out.println("Data Criacao:" + txtData_Criacao.getText());
        txtUsuario_Criacao.setText(Tela_Login.objMenu.mLoginUsuario);
        btConfirmar.setEnabled(vSelecao);
        btCancela.setEnabled(vSelecao);

        if (LimpaTudo == true){
            AtualizaEquipes();
            jpManutencao.setEnabled(false);
            tbpEquipes.setSelectedIndex(0);
            txtCampoPesquisa.requestFocus();
            btNovo.setVisible(true);
            btAdicionar.setVisible(false);
            btAlterar.setVisible(false);
            btExcluir.setVisible(false);
        }
        if (NovoRegistro == true){
            tbpEquipes.setSelectedIndex(1);
            txtNome_Equipe.requestFocus();
            btNovo.setVisible(false);
            btAdicionar.setVisible(true);
            btAlterar.setVisible(false);
            btExcluir.setVisible(false);
            jpManutencao.setEnabled(true);
        }
    
   }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Equipes("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterar;
    public static javax.swing.JButton btCancela;
    public static javax.swing.JButton btConfirmar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JComboBox cbPesquisarPor;
    private javax.swing.JTable dtgEquipes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpManutencao;
    private javax.swing.JLayeredPane pnlConsulta;
    private javax.swing.JLayeredPane pnlManutencao;
    private javax.swing.JRadioButton rbComecandoPor;
    private javax.swing.JRadioButton rbContendo;
    private javax.swing.JTabbedPane tbpEquipes;
    private javax.swing.JTextField txtBairro_Equipe;
    private javax.swing.JTextField txtCampoPesquisa;
    private javax.swing.JFormattedTextField txtData_Criacao;
    private javax.swing.JTextField txtEndereco_Equipe;
    private javax.swing.JTextField txtId_Equipe;
    private javax.swing.JTextField txtNome_Equipe;
    private javax.swing.JFormattedTextField txtSituacao;
    private javax.swing.JFormattedTextField txtTelefone_Equipe;
    private javax.swing.JFormattedTextField txtUsuario_Criacao;
    // End of variables declaration//GEN-END:variables

}
