/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Usuarios.java
 *
 * Created on 13/03/2011, 18:46:50
 */

package Interface;

import Modelo.Usuarios;
import Modelo.ConexaoBD;
import Controle.Controla_Usuarios;
import Ferramentas.CaixaDeDialogo;
import Ferramentas.Formatacao;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;

/**
 *
 * @author Jonas
 */
public class Tela_Usuarios extends javax.swing.JFrame {
     Menu objMenu;
     public static Connection con;
     public static Statement stmt;
     //Usuarios objUsuario = null;
     Controla_Usuarios ctlUsuario;
     Usuarios Usuarios = new Usuarios();
     private JFormattedTextField txtLogin_Usuario;

    /** Creates new form Usuarios */
    public Tela_Usuarios() {
        abreConexao();
        this.setLocation(20, 100);
        initComponents();
  
        LimpaTela(true,false);

    }

//    public Usuarios(Usuarios objUsuario) {
//        this.objUsuario = objUsuario;
//    }


    private void abreConexao() {
        try {
        con = ConexaoBD.getInstance().getConnection();
        stmt = con.createStatement();
        System.out.print("Conexão com Banco de Dados Criada!");
        } catch (Exception e) {
        System.out.print(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        tbpUsuarios = new javax.swing.JTabbedPane();
        pnlConsulta = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbPesquisarPor = new javax.swing.JComboBox();
        txtCampoPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtgUsuarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        rbComecandoPor = new javax.swing.JRadioButton();
        rbContendo = new javax.swing.JRadioButton();
        pnlManutencao = new javax.swing.JLayeredPane();
        jpManutencao = new javax.swing.JPanel();
        txtId_Usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome_Usuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtData_Criacao = new javax.swing.JFormattedTextField();
        txtLogin_Usuario = Formatacao.getTelefone();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario_Criacao = new javax.swing.JFormattedTextField();
        txtLogin_Usuario = Formatacao.getTelefone();
        jLabel7 = new javax.swing.JLabel();
        txtSituacao = new javax.swing.JFormattedTextField();
        txtLogin_Usuario = Formatacao.getTelefone();
        lblLogin2 = new javax.swing.JLabel();
        lblLogin3 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha1 = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JPasswordField();
        btConfirmar = new javax.swing.JButton();
        btCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuarios");
        setMinimumSize(new java.awt.Dimension(660, 469));
        setPreferredSize(new java.awt.Dimension(660, 469));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Confirma.png"))); // NOI18N
        btAdicionar.setText("Adicionar");
        btAdicionar.setPreferredSize(new java.awt.Dimension(77, 25));
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Lapis2.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setPreferredSize(new java.awt.Dimension(77, 25));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Novo.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setPreferredSize(new java.awt.Dimension(77, 25));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Porta.PNG"))); // NOI18N
        btFechar.setText("Fechar");
        btFechar.setPreferredSize(new java.awt.Dimension(77, 25));
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Exclui.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setPreferredSize(new java.awt.Dimension(77, 25));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Mais.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovo)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 11, 633, 47);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar Por");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPesquisar))
                    .addComponent(txtCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlConsulta.add(jPanel2);
        jPanel2.setBounds(10, 10, 450, 90);

        dtgUsuarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dtgUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtgUsuariosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dtgUsuariosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(dtgUsuarios);

        pnlConsulta.add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 610, 240);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        rbComecandoPor.setSelected(true);
        rbComecandoPor.setText("Começando Por");
        rbComecandoPor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbComecandoPorStateChanged(evt);
            }
        });

        rbContendo.setText("Contendo");
        rbContendo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbContendoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rbContendo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbComecandoPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbComecandoPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(rbContendo)
                .addContainerGap())
        );

        pnlConsulta.add(jPanel3);
        jPanel3.setBounds(460, 10, 160, 90);

        tbpUsuarios.addTab("Consulta", pnlConsulta);

        pnlManutencao.setEnabled(false);

        jpManutencao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpManutencao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId_Usuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId_Usuario.setEnabled(false);
        jpManutencao.add(txtId_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 32, 60, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Nome Usuário");
        jpManutencao.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 58, 102, 20));

        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLogin.setText("Login");
        jpManutencao.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 84, 103, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Id Usuário");
        jpManutencao.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 32, 102, 20));

        txtNome_Usuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jpManutencao.add(txtNome_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 58, 210, -1));

        jLabel5.setText("Data de Criação");
        jpManutencao.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 240, 86, 20));

        txtData_Criacao.setEditable(false);
        jpManutencao.add(txtData_Criacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 240, 120, -1));

        jLabel6.setText("Usuário Criação");
        jpManutencao.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 266, 87, 20));

        txtUsuario_Criacao.setEditable(false);
        jpManutencao.add(txtUsuario_Criacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 266, 120, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Situação");
        jpManutencao.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 174, 103, 20));

        txtSituacao.setEditable(false);
        jpManutencao.add(txtSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 174, 116, -1));

        lblLogin2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLogin2.setText("Confirmação Senha");
        jpManutencao.add(lblLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 136, 103, 20));

        lblLogin3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLogin3.setText("Senha");
        jpManutencao.add(lblLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 110, 103, 20));

        txtLogin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jpManutencao.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 84, 116, -1));

        txtSenha1.setText("*****");
        jpManutencao.add(txtSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 136, 116, -1));

        txtSenha.setText("*****");
        jpManutencao.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 116, -1));

        pnlManutencao.add(jpManutencao);
        jpManutencao.setBounds(10, 10, 610, 310);

        btConfirmar.setText("Confirma");
        btConfirmar.setPreferredSize(new java.awt.Dimension(77, 25));
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });
        pnlManutencao.add(btConfirmar);
        btConfirmar.setBounds(430, 330, 90, 20);

        btCancela.setText("Cancela");
        btCancela.setPreferredSize(new java.awt.Dimension(77, 25));
        btCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaActionPerformed(evt);
            }
        });
        pnlManutencao.add(btCancela);
        btCancela.setBounds(530, 330, 90, 20);

        tbpUsuarios.addTab("Manutenção", pnlManutencao);

        getContentPane().add(tbpUsuarios);
        tbpUsuarios.setBounds(10, 69, 633, 378);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int wControle = 0;

        wControle = Tela_Login.objMenu.preencheJanelas("Usuarios", "I");
            if (wControle != 0){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Usuários'");
            }
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        int wControle = 0;

        wControle = Tela_Login.objMenu.preencheJanelas("Usuarios", "I");
            if (wControle != 0){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Usuários'");
            }
        dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        int wControle = 0;
        String xMensagemValidacao = "";

        xMensagemValidacao = ValidaDados();
        if (xMensagemValidacao.equals("")){
        System.out.println("Validou Dados");

        Usuarios.definirId_Usuario(Integer.parseInt(txtId_Usuario.getText()));
        GuardaDados(false);
        System.out.println("Guardou Dados");

        wControle = ctlUsuario.alterarUsuario();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Usuario alterado com sucesso!");
           LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao alterar Usuario!");
           }
        } else {
        CaixaDeDialogo.obterinstancia().exibirMensagem("Erros de Validação: \n" + xMensagemValidacao);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        LimpaTela(true,false);
    }//GEN-LAST:event_btLimparActionPerformed

    private void dtgUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgUsuariosMouseClicked
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_dtgUsuariosMouseClicked

    private void dtgUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgUsuariosMousePressed
        // TODO add your handling code here:
        int wControle;
        int linhaSelecionada = dtgUsuarios.getSelectedRow();//pega a linha selecionada
        String coluna1 = dtgUsuarios.getModel().getValueAt(linhaSelecionada, 0).toString(); // Primeira coluna da linha
        
        if (dtgUsuarios.isColumnSelected(3)){
            tbpUsuarios.setSelectedIndex(1);
            txtNome_Usuario.requestFocus();
            btAlterar.setVisible(true);
            btExcluir.setVisible(true);
            btNovo.setVisible(true);
            btAdicionar.setVisible(false);

            ctlUsuario = new Controla_Usuarios(Usuarios, dtgUsuarios);

            Usuarios.definirId_Usuario(Integer.parseInt(coluna1));
            wControle = ctlUsuario.buscarUsuario();
                if (wControle < 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao buscar Usuario no BD!");
                } else {
                if (wControle == 0)
                TelaAlteracao();
                }
     }
    }//GEN-LAST:event_dtgUsuariosMousePressed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelaActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        LimpaTela(true,true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        int wControle = 0;
        String xMensagemValidacao = "";
        
        xMensagemValidacao = ValidaDados();
        if (xMensagemValidacao.equals("")){
        System.out.println("Validou Dados");
        GuardaDados(true);
        System.out.println("Guardou Dados");

        wControle = ctlUsuario.gravarUsuario();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Usuario gravado com sucesso!");
            LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao gravar Usuario!");
           }
        } else {
        CaixaDeDialogo.obterinstancia().exibirMensagem("Erros de Validação: \n" + xMensagemValidacao);
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int wControle = 0;
        char wChar = 'p';
        boolean wPergunta = false;

        wPergunta = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Tem certeza de que deseja excluir o Usuário?","",wChar);

        if (wPergunta == true){
        Usuarios.definirId_Usuario(Integer.parseInt(txtId_Usuario.getText()));
        Usuarios.definirUsuario_Exclusao(Tela_Login.objMenu.mIdUsuarioLogin);
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        formatador.format(data);
        Usuarios.definirData_Exclusao(formatador.format(data));
        wControle = ctlUsuario.excluirUsuario();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Usuário excluído com sucesso!");
           LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao excluir Usuário!");
          }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String pTipoSelecao = "";
        if (rbComecandoPor.isSelected()){
           pTipoSelecao = "CP";
        } else {
           pTipoSelecao = "CT";
        }

        ctlUsuario.PreencheUsuarios(cbPesquisarPor.getSelectedItem().toString(),txtCampoPesquisa.getText(), pTipoSelecao);
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void rbComecandoPorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbComecandoPorStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbComecandoPorStateChanged

    private void rbContendoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbContendoStateChanged
        // TODO add your handling code here:
        //rbComecandoPor.setSelected(false);
        //rbContendo.setSelected(true);
}//GEN-LAST:event_rbContendoStateChanged

    private void AtualizaUsuarios(){
        //objUsuarios.setNome(txNomeMotorista.getText());
        //objUsuarios.definirNome_Usuario('teste');
        //objUsuarios.definirTelefone('teste');
        //objUsuarios.setCategoriaCarteira('teste');
        ctlUsuario = new Controla_Usuarios(Usuarios, dtgUsuarios);
        
        //wControle = objUsuarios_Implem.buscaUsuarios();
        ctlUsuario.PreencheUsuarios("","","");
        PreencheComboPesquisa();
    }

        private void PreencheComboPesquisa(){

        cbPesquisarPor.removeAllItems();
        if ((dtgUsuarios.getColumnCount() - 1) > 0){
            for (int i= 0; i < dtgUsuarios.getColumnCount() - 1; i++){
              cbPesquisarPor.addItem(dtgUsuarios.getColumnName(i));
            }
        }
    }

        private String ValidaDados() {
        String xMensagem = "";
        
        if(txtNome_Usuario.getText().equals("")){
        xMensagem +="Nome Usuário deve ser preenchido! \n";
        }

        if(txtLogin.getText().equals("")){
        xMensagem +="Login Usuário deve ser preenchido! \n";
        }

        System.out.println("Senha: " + txtSenha.getText());
        System.out.println("Senha1: " + txtSenha1.getText());

        if(txtSenha.getText() != ""){
            if(!txtSenha.getText().equals(txtSenha1.getText())){
            xMensagem +="Senhas não conferem! \n";
            }
        } else {
         xMensagem += "Senha do Usuário deve ser preenchida! \n";
        }
      
        return xMensagem;
     }

        private void GuardaDados(boolean RegistroNovo) {

        if (RegistroNovo == true){
        System.out.println("Guardou Dados true");
        Usuarios.definirId_Usuario(0);
        Usuarios.definirUsuario_Criacao(Tela_Login.objMenu.mIdUsuarioLogin);
        Usuarios.definirData_Criacao(txtData_Criacao.getText());

        Usuarios.definirNome_Usuario(txtNome_Usuario.getText());
        Usuarios.definirLogin_Usuario(txtLogin.getText());
        //Usuarios.definirSituacao_Usuario();
        Usuarios.definirSenha_Usuario(txtSenha.getText());
        } else {
        System.out.println("Guardou Dados false");
        Usuarios.definirNome_Usuario(txtNome_Usuario.getText());
        Usuarios.definirLogin_Usuario(txtLogin.getText());
        Usuarios.definirSenha_Usuario(txtSenha.getText());
        }
        //ctlUsuario = new Controla_Usuarios(Usuarios, dtgUsuarios);
        
    }

    private void TelaAlteracao() {

        pnlManutencao.setEnabled(true);
        txtId_Usuario.setText(Integer.toString(Usuarios.obterId_Usuario()));
        txtNome_Usuario.setText(Usuarios.obterNome_Usuario());
        txtLogin.setText(Usuarios.obterlogin_Usuario());
        txtSenha.setText(Usuarios.obterSenha_Usuario());
        txtSenha1.setText(Usuarios.obterSenha_Usuario());

        if (Usuarios.obterData_Exclusao() == null){
            txtSituacao.setText("ATIVO");
        } else {
            txtSituacao.setText("EXCLUÍDO");
        }
    }

    private void LimpaTela(boolean LimpaTudo, boolean NovoRegistro) {

        txtCampoPesquisa.setText("");
        txtId_Usuario.setText("");
        txtNome_Usuario.setText("");
        txtLogin.setText("");
        txtSenha.setText("");
        txtSenha1.setText("");
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        formatador.format(data);
        txtData_Criacao.setText(formatador.format(data));
        txtUsuario_Criacao.setText(Tela_Login.objMenu.mLoginUsuario);
        
        if (LimpaTudo == true){
            AtualizaUsuarios();
            jpManutencao.setEnabled(false);
            tbpUsuarios.setSelectedIndex(0);
            txtCampoPesquisa.requestFocus();
            btNovo.setVisible(true);
            btAdicionar.setVisible(false);
            btAlterar.setVisible(false);
            btExcluir.setVisible(false);
        }
        if (NovoRegistro == true){
            tbpUsuarios.setSelectedIndex(1);
            txtNome_Usuario.requestFocus();
            btNovo.setVisible(false);
            btAdicionar.setVisible(true);
            btAlterar.setVisible(false);
            btExcluir.setVisible(false);
            jpManutencao.setEnabled(true);
        }
    
   }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancela;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JComboBox cbPesquisarPor;
    private javax.swing.JTable dtgUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpManutencao;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogin2;
    private javax.swing.JLabel lblLogin3;
    private javax.swing.JLayeredPane pnlConsulta;
    private javax.swing.JLayeredPane pnlManutencao;
    private javax.swing.JRadioButton rbComecandoPor;
    private javax.swing.JRadioButton rbContendo;
    private javax.swing.JTabbedPane tbpUsuarios;
    private javax.swing.JTextField txtCampoPesquisa;
    private javax.swing.JFormattedTextField txtData_Criacao;
    private javax.swing.JTextField txtId_Usuario;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome_Usuario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenha1;
    private javax.swing.JFormattedTextField txtSituacao;
    private javax.swing.JFormattedTextField txtUsuario_Criacao;
    // End of variables declaration//GEN-END:variables

}
