/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.

 * Equipes.java
 *
 * Created on 13/03/2011, 18:46:50
*/

package Interface;

import Controle.Controla_Avaliacoes;
import Controle.Controla_Avaliacoes_Equipe;
import Modelo.Equipes;
import Modelo.ConexaoBD;
import Controle.Controla_Equipes;
import Ferramentas.CaixaDeDialogo;
import Ferramentas.DLLInterface;
import Ferramentas.Formatacao;
import Ferramentas.Validacao;
import Modelo.Avaliacoes;
import Modelo.Avaliacoes_Equipe;
import java.awt.EventQueue;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JFormattedTextField;

/**
 *
 * @author Jonas
 */
public class Tela_Avaliacoes extends javax.swing.JFrame {
     Menu objMenu;
     DLLInterface DLLInterface;
     public static Connection con;
     public static Statement stmt;
     public boolean vSelecao = true;
     //Equipes objEquipe = null;
     Controla_Equipes ctlEquipe;
     Equipes Equipes = new Equipes();
     
     Controla_Avaliacoes ctlAvaliacoes;
     Avaliacoes avaliacoes = new Avaliacoes();
     
     Controla_Avaliacoes_Equipe ctlAvaliacoes_Equipe;
     Avaliacoes_Equipe avaliacao_Equipe = new Avaliacoes_Equipe();
    
     private JFormattedTextField txtTelefone_Equipe;
     private JFormattedTextField txtTelefone_Cliente;
          
    /** Creates new form Equipes */
    public Tela_Avaliacoes(String pPesquisa) {
        abreConexao();
        this.setLocation(20, 100);
        initComponents();

        ButtonGroup bg= new ButtonGroup();
        bg.add(rbComecandoPor); // jRadioButton1
        bg.add(rbContendo); // jRadioButton2

        LimpaTela(true,false);
        txtCampoPesquisa.setText(pPesquisa);
        
        System.out.print("pPesquisa = " + pPesquisa);
        cbPesquisarPor.setSelectedItem("Nome_Equipe");
        btPesquisarActionPerformed(null);
        

    }

//    public Equipes(Equipes objEquipe) {
//        this.objEquipe = objEquipe;
//    }


    private void abreConexao() {
        try {
        con = ConexaoBD.getInstance().getConnection();
        stmt = con.createStatement();
        System.out.print("Conexão com Banco de Dados Criada!");
        } catch (Exception e) {
        System.out.print(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btAlterar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        tbpAvaliacoes = new javax.swing.JTabbedPane();
        pnlConsulta = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        rbComecandoPor = new javax.swing.JRadioButton();
        rbContendo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtgAvaliacoes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbPesquisarPor = new javax.swing.JComboBox();
        txtCampoPesquisa = new javax.swing.JTextField();
        pnlManutencao = new javax.swing.JLayeredPane();
        jpManutencao = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dtgResultados = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId_Prova = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtData_Criacao = new javax.swing.JFormattedTextField();
        txtTelefone_Cliente = Formatacao.getTelefone();
        jLabel4 = new javax.swing.JLabel();
        txtId_Equipe = new javax.swing.JTextField();
        txtNome_Equipe = new javax.swing.JTextField();
        btNovo1 = new javax.swing.JButton();
        btPesquisarEquipe = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPeso_Ponte = new javax.swing.JTextField();
        lblPorta = new javax.swing.JLabel();
        txtPorta = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btIniciaTimer = new javax.swing.JButton();
        lblPesoSuportado = new javax.swing.JLabel();
        lblTimer1 = new javax.swing.JLabel();
        lblAprovado = new javax.swing.JLabel();
        btExcluir1 = new javax.swing.JButton();
        btAdicionarEquipe = new javax.swing.JButton();
        btExcluirEquipe = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lblLista1 = new javax.swing.JLabel();
        lblLista2 = new javax.swing.JLabel();
        lblLista4 = new javax.swing.JLabel();
        lblLista3 = new javax.swing.JLabel();
        lblPosicaoAtual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Avaliações");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Lapis2.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setPreferredSize(new java.awt.Dimension(77, 25));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Novo.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setPreferredSize(new java.awt.Dimension(77, 25));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Porta.PNG"))); // NOI18N
        btFechar.setText("Fechar");
        btFechar.setPreferredSize(new java.awt.Dimension(77, 25));
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Mais.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Exclui.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setPreferredSize(new java.awt.Dimension(77, 25));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 620, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        rbComecandoPor.setSelected(true);
        rbComecandoPor.setText("Começando Por");
        rbComecandoPor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbComecandoPorStateChanged(evt);
            }
        });

        rbContendo.setText("Contendo");
        rbContendo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbContendoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rbContendo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbComecandoPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbComecandoPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(rbContendo)
                .addContainerGap())
        );

        pnlConsulta.add(jPanel2);
        jPanel2.setBounds(360, 0, 360, 90);
        jPanel2.getAccessibleContext().setAccessibleName("Seleção");

        dtgAvaliacoes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dtgAvaliacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtgAvaliacoesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dtgAvaliacoesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(dtgAvaliacoes);

        pnlConsulta.add(jScrollPane1);
        jScrollPane1.setBounds(0, 90, 720, 310);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jLabel8.setText("Pesquisar Por");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPesquisar))
                    .addComponent(txtCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlConsulta.add(jPanel3);
        jPanel3.setBounds(0, 0, 360, 90);

        tbpAvaliacoes.addTab("Consulta", pnlConsulta);

        pnlManutencao.setEnabled(false);

        jpManutencao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpManutencao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        dtgResultados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dtgResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtgResultadosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dtgResultadosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(dtgResultados);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );

        jpManutencao.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 340, 380));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel2.setText("Id");

        txtId_Prova.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId_Prova.setEnabled(false);

        jLabel5.setText("Data");

        txtData_Criacao.setEditable(false);

        jLabel4.setText("Equipe");

        txtId_Equipe.setEditable(false);
        txtId_Equipe.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtNome_Equipe.setEditable(false);
        txtNome_Equipe.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Mais.png"))); // NOI18N
        btNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo1ActionPerformed(evt);
            }
        });

        btPesquisarEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lupa.png"))); // NOI18N
        btPesquisarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarEquipeActionPerformed(evt);
            }
        });

        jLabel6.setText("Peso da Ponte (Kg)");

        txtPeso_Ponte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblPorta.setText("PORTA");

        txtPorta.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(txtId_Prova, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtData_Criacao, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtId_Equipe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtNome_Equipe, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisarEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPeso_Ponte, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPorta)
                        .addGap(6, 6, 6)
                        .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addComponent(btNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId_Prova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtData_Criacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId_Equipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNome_Equipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btPesquisarEquipe))
                    .addComponent(btNovo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPeso_Ponte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpManutencao.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 110));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Prova"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btIniciaTimer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btIniciaTimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/timer.png"))); // NOI18N
        btIniciaTimer.setText("START");
        btIniciaTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciaTimerActionPerformed(evt);
            }
        });
        jPanel6.add(btIniciaTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 45));

        lblPesoSuportado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPesoSuportado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPesoSuportado.setText("55.4");
        lblPesoSuportado.setOpaque(true);
        jPanel6.add(lblPesoSuportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 110, 40));

        lblTimer1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTimer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimer1.setText("10");
        lblTimer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(lblTimer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 60, 40));

        lblAprovado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAprovado.setForeground(new java.awt.Color(0, 204, 0));
        lblAprovado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAprovado.setText("PESO APROVADO");
        jPanel6.add(lblAprovado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 110, 20));

        btExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Exclui.png"))); // NOI18N
        btExcluir1.setText("Problema");
        btExcluir1.setPreferredSize(new java.awt.Dimension(77, 25));
        btExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluir1ActionPerformed(evt);
            }
        });
        jPanel6.add(btExcluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 100, -1));

        btAdicionarEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Confirma.png"))); // NOI18N
        btAdicionarEquipe.setText("Adicionar");
        btAdicionarEquipe.setOpaque(false);
        btAdicionarEquipe.setPreferredSize(new java.awt.Dimension(77, 25));
        btAdicionarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarEquipeActionPerformed(evt);
            }
        });
        jPanel6.add(btAdicionarEquipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, -1));

        btExcluirEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Exclui.png"))); // NOI18N
        btExcluirEquipe.setText("Excluir");
        btExcluirEquipe.setPreferredSize(new java.awt.Dimension(77, 25));
        btExcluirEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirEquipeActionPerformed(evt);
            }
        });
        jPanel6.add(btExcluirEquipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 94, -1));

        jpManutencao.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 350, 140));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Próximas Equipes"));
        jPanel7.setLayout(null);

        lblLista1.setText("1 - Equipe Alfa");
        jPanel7.add(lblLista1);
        lblLista1.setBounds(10, 20, 140, 20);

        lblLista2.setText("2 - Equipe Delta");
        jPanel7.add(lblLista2);
        lblLista2.setBounds(10, 40, 140, 20);

        lblLista4.setText("4 - Equipe Nova");
        jPanel7.add(lblLista4);
        lblLista4.setBounds(170, 40, 140, 20);

        lblLista3.setText("3 - Equipe Charli");
        jPanel7.add(lblLista3);
        lblLista3.setBounds(170, 20, 140, 20);

        jpManutencao.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 350, 70));

        lblPosicaoAtual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPosicaoAtual.setForeground(new java.awt.Color(51, 51, 255));
        lblPosicaoAtual.setText("PosiçãoAtual:");
        jpManutencao.add(lblPosicaoAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 330, -1));

        pnlManutencao.add(jpManutencao);
        jpManutencao.setBounds(0, 0, 720, 400);

        tbpAvaliacoes.addTab("Manutenção", pnlManutencao);

        getContentPane().add(tbpAvaliacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, 730, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int wControle = 0;

        wControle = Tela_Login.objMenu.preencheJanelas("Equipes", "I");
            if (wControle != 0){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Equipes'");
            }
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        int wControle = 0;
//
//        wControle = Tela_Login.objMenu.preencheJanelas("Equipes", "I");
//            if (wControle != 0){
//            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Equipes'");
//            }
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        int wControle = 0;

        wControle = Tela_Login.objMenu.preencheJanelas("Avaliacoes", "I");
            if (wControle != 0){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Avaliacoes'");
            }
        dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        int wControle = 0;
        String xMensagemValidacao = "";

        xMensagemValidacao = ValidaDados();
        if (xMensagemValidacao.equals("")){
        System.out.println("Validou Dados");

        Equipes.definirId_Equipe(Integer.parseInt(txtId_Prova.getText()));
        //Equipes.definirNome_Equipe(txtNome_Equipe.getText());
        //Equipes.definirTelefone(txtTelefone_Equipe.getText().replace("(","").replace(")","").replace("-",""));
        GuardaDados(false);
        System.out.println("Guardou Dados");

        wControle = ctlEquipe.alterarEquipe();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Equipe alterado com sucesso!");
           LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao alterar cliente!");
           }
        } else {
        CaixaDeDialogo.obterinstancia().exibirMensagem("Erros de Validação: \n" + xMensagemValidacao);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        LimpaTela(true,false);
    }//GEN-LAST:event_btLimparActionPerformed

    private void dtgAvaliacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgAvaliacoesMouseClicked
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_dtgAvaliacoesMouseClicked

    private void dtgAvaliacoesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgAvaliacoesMousePressed
        // TODO add your handling code here:
        int wControle;
        int linhaSelecionada = dtgAvaliacoes.getSelectedRow();//pega a linha selecionada
        String coluna1 = dtgAvaliacoes.getModel().getValueAt(linhaSelecionada, 0).toString(); // Primeira coluna da linha
        
        if (dtgAvaliacoes.isColumnSelected(2)){
            tbpAvaliacoes.setSelectedIndex(1);
            txtNome_Equipe.requestFocus();
            btAlterar.setVisible(true);
            //btExcluir.setVisible(true);
            //btNovo.setVisible(true);
            btAdicionarEquipe.setVisible(false);

            ctlAvaliacoes = new Controla_Avaliacoes(avaliacoes, dtgAvaliacoes);

            avaliacoes.definirId_Avaliacao(Integer.parseInt(coluna1));
            wControle = ctlAvaliacoes.buscarAvaliacao();
                if (wControle < 0){
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao buscar Prova no BD!");
                } else {
                    if (wControle == 0)
                    TelaAlteracao();
                    //AtualizaAvaliacoesEquipes();
                }
        }
    }//GEN-LAST:event_dtgAvaliacoesMousePressed
    
    private void AdicionarEquipe(){
        try{
            int wControle = 0;
            String xMensagemValidacao = "";

            xMensagemValidacao = ValidaDados();
            if (xMensagemValidacao.equals("")){
                System.out.println("Validou Dados");
                GuardaDadosAvaliacaoEquipe(true, "");
                System.out.println("Guardou Dados");

                wControle = ctlAvaliacoes_Equipe.gravarAvaliacao_Equipe();
                if (wControle != 0){
                   CaixaDeDialogo.obterinstancia().exibirMensagem("Avaliação gravada com sucesso!");
                    LimpaTela(false,false);
                } else {
                   CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao gravar Avaliação!");
                   }
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erros de Validação: \n" + xMensagemValidacao);
            }
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Ocorreu um erro: \n" + ex.getMessage().toString());
        }
    }
    
    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int wControle = 0;

        char wChar = 'p';
        boolean wPergunta = false;

        wPergunta = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Tem certeza de que deseja excluir a Avaliação?","",wChar);

        if (wPergunta == true){
            Equipes.definirId_Equipe(Integer.parseInt(txtId_Prova.getText()));
            Equipes.definirUsuario_Exclusao(Tela_Login.objMenu.mIdUsuarioLogin);
            Date data = new Date();
            SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
            formatador.format(data);
            Equipes.definirData_Exclusao(formatador.format(data));
            wControle = ctlEquipe.excluirEquipe();
            if (wControle != 0){
               CaixaDeDialogo.obterinstancia().exibirMensagem("Equipe excluído com sucesso!");
               LimpaTela(true,false);
            } else {
               CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao excluir cliente!");
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        String pTipoSelecao = "";
        if (rbComecandoPor.isSelected()){
           pTipoSelecao = "CP";
        } else {
           pTipoSelecao = "CT";
        }

        ctlAvaliacoes.PreencheAvaliacoes(cbPesquisarPor.getSelectedItem().toString(),txtCampoPesquisa.getText(), pTipoSelecao);
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void rbComecandoPorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbComecandoPorStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbComecandoPorStateChanged

    private void rbContendoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbContendoStateChanged
        // TODO add your handling code here:
        //rbComecandoPor.setSelected(false);
        //rbContendo.setSelected(true);
    }//GEN-LAST:event_rbContendoStateChanged

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        int wControle;
        
        try{
            
            LimpaTela(true,true);

            GuardaDados(true);
            System.out.println("Guardou Dados");

            wControle = ctlAvaliacoes.gravarAvaliacao();
            if (wControle != 0){
               CaixaDeDialogo.obterinstancia().exibirMensagem("Avaliação gravada com sucesso!");
               
               avaliacoes.definirId_Avaliacao(wControle);
               wControle = ctlAvaliacoes.buscarAvaliacao();
                if (wControle < 0){
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao buscar Avaliação no BD!");
                } else {
                if (wControle == 0)
                    TelaAlteracao();
                }
                
            } else {
               CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao gravar Avaliação!");
            }
            
        }catch(Exception ex){
            
        }
        
    }//GEN-LAST:event_btNovoActionPerformed

    private void btNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNovo1ActionPerformed

    private void dtgResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgResultadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dtgResultadosMouseClicked

    private void dtgResultadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgResultadosMousePressed
        int wControle;
        int linhaSelecionada = dtgResultados.getSelectedRow();//pega a linha selecionada
        String coluna1 = dtgResultados.getModel().getValueAt(linhaSelecionada, 0).toString(); // Primeira coluna da linha
        //String coluna2 = dtgResultados.getModel().getValueAt(linhaSelecionada, 1).toString(); // SEgunda coluna da linha
        
        if (dtgResultados.isColumnSelected(3)){
            //tbpAvaliacoes.setSelectedIndex(1);
            //txtNome_Equipe.requestFocus();
            //btAlterar.setVisible(true);
            btExcluirEquipe.setVisible(true);
            //btNovo.setVisible(true);
            btAdicionarEquipe.setVisible(false);

            ctlAvaliacoes_Equipe = new Controla_Avaliacoes_Equipe(avaliacao_Equipe, dtgResultados);

            avaliacao_Equipe.definirId_Avaliacao(Integer.parseInt(txtId_Prova.getText()));
            avaliacao_Equipe.definirId_Equipe(Integer.parseInt(coluna1));
            wControle = ctlAvaliacoes_Equipe.buscarAvaliacao_Equipe();
                if (wControle < 0){
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao buscar Prova no BD!");
                } else {
                    if (wControle == 0)
                    txtId_Equipe.setText(Integer.toString(avaliacao_Equipe.obterId_Equipe()));
                    txtId_Prova.setText(Integer.toString(avaliacao_Equipe.obterId_Avaliacao()));
                    txtNome_Equipe.setText(avaliacao_Equipe.obterNome_Equipe());
                    txtPeso_Ponte.setText(Double.toString(avaliacao_Equipe.obterPeso_Ponte()));
                }
        }
    }//GEN-LAST:event_dtgResultadosMousePressed

    private void btIniciaTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciaTimerActionPerformed
        try{
            double wPeso;
            int wControle;
            lblAprovado.setText("");
            Cronometro();
        
            int wPorta = Integer.parseInt(txtPorta.getText());
            wPeso = DLLInterface.BalancaLider.CapturarPeso(wPorta, 9600);
            
            if (wPeso > Double.parseDouble(lblPesoSuportado.getText())){
                lblPesoSuportado.setOpaque(false);
                lblPesoSuportado.setText(wPeso + "");
                lblAprovado.setText("PESO APROVADO");
            } else{
                lblAprovado.setText("PESO NÃO VALIDADO");
                
                //salva o resultado
                GuardaDadosAvaliacaoEquipe(true, "");
                wControle = ctlAvaliacoes_Equipe.gravarAvaliacao_Equipe();
            }
            
            //busca a posicao atraves da variavel wPeso
            lblPesoSuportado.setText("No momento a equipe ocupa a " + 1 + "ª posição!");
            
            //wControle2 = Integer.parseInt(DLLInterface.BalancaLider.CapturarPeso(4, 9600) + "");
            //wControle = DLLInterface.BalancaLider.CapturarPeso(Integer.parseInt(txtPorta.getText()), Integer.parseInt(txtVelocidade.getText()));
            wPeso = DLLInterface.BalancaLider.Zerar(Integer.parseInt(txtPorta.getText()), 9600);
            
        } catch(Exception ex){
            System.out.println("ERRO NO BOTÃO TIMER: " + ex.getMessage());
        }        
        
    }//GEN-LAST:event_btIniciaTimerActionPerformed

    private void btExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluir1ActionPerformed

    private void btPesquisarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarEquipeActionPerformed
        Tela_Equipes objEquipes;
        objEquipes = new Tela_Equipes(txtNome_Equipe.getText());
        objEquipes.vSelecao = true;
        objEquipes.btCancela.setEnabled(true);
        objEquipes.btConfirmar.setEnabled(true);
        objEquipes.setVisible(true);
    }//GEN-LAST:event_btPesquisarEquipeActionPerformed

    private void btAdicionarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarEquipeActionPerformed
        AdicionarEquipe();
        AtualizaAvaliacoesEquipes();
    }//GEN-LAST:event_btAdicionarEquipeActionPerformed

    private void btExcluirEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirEquipeActionPerformed

    public static void RecebeEquipe(String Cod_Equipe, String Nome_Equipe, String Participantes_Equipe){
        txtId_Equipe.setText(Cod_Equipe);
        txtNome_Equipe.setText(Nome_Equipe);
        //txtTelefone_Cliente.setText(Participantes_Equipe);
    }
        
    private void AtualizaAvaliacoes(){
        //objEquipes.setNome(txNomeMotorista.getText());
        //objEquipes.definirNome_Equipe('teste');
        //objEquipes.definirTelefone('teste');
        //objEquipes.setCategoriaCarteira('teste');
        ctlAvaliacoes = new Controla_Avaliacoes(avaliacoes, dtgAvaliacoes);
        
        //wControle = objEquipes_Implem.buscaEquipes();
        ctlAvaliacoes.PreencheAvaliacoes("","","");
        PreencheComboPesquisa();
    }
    
    private void Cronometro(){
        int tempo = 10;                    
        try {  

            while (true) {  
                EventQueue.invokeLater(new Runnable() {  
                    public void run() {                                
                    }  
                }); 
                Thread.sleep(1000);  
                tempo = tempo - 1;
                lblTimer1.setText(tempo + "");
                
                if (tempo == 0)
                    break;
            }  
        }  
        catch (InterruptedException e) {  
        }  
    }
    
    private void AtualizaAvaliacoesEquipes(){
        //objEquipes.setNome(txNomeMotorista.getText());
        //objEquipes.definirNome_Equipe('teste');
        //objEquipes.definirTelefone('teste');
        //objEquipes.setCategoriaCarteira('teste');
        avaliacao_Equipe.definirId_Avaliacao(avaliacoes.obterId_Avaliacao());
        ctlAvaliacoes_Equipe = new Controla_Avaliacoes_Equipe(avaliacao_Equipe, dtgResultados);
        
        //wControle = objEquipes_Implem.buscaEquipes();
        ctlAvaliacoes_Equipe.PreencheAvaliacoes_Equipe(avaliacoes.obterId_Avaliacao());
        //PreencheComboPesquisa();
    }

        private void PreencheComboPesquisa(){

        cbPesquisarPor.removeAllItems();
        if ((dtgAvaliacoes.getColumnCount() - 1) > 0){
            for (int i= 0; i < dtgAvaliacoes.getColumnCount() - 1; i++){
              cbPesquisarPor.addItem(dtgAvaliacoes.getColumnName(i));
            }
        }
        
    }

        private String ValidaDados() {
        String xMensagem = "";
        
        if(txtNome_Equipe.getText().equals("")){
            xMensagem +="Nome Equipe deve ser preenchido! \n";
        }

        if( txtPeso_Ponte.getText().equals("")){
            xMensagem +="Peso da Ponte em Kg deve ser preenchido! \n";
        }
        
        return xMensagem;
     }

    private void GuardaDados(boolean RegistroNovo) {

        if (RegistroNovo == true){
            System.out.println("Guardou Dados Registro Novo = true");
            avaliacoes.definirId_Avaliacao(0);
            avaliacoes.definirData_Criacao(txtData_Criacao.getText());
            avaliacoes.definirData_Avaliacao(txtData_Criacao.getText());
            avaliacoes.definirUsuario_Criacao(Tela_Login.objMenu.mIdUsuarioLogin);
            System.out.println("definirData_Criacao = " + txtData_Criacao.getText());
        } else {
            //A PRINCIPIO NAO PODE ALTERAR UMA PROVA
        }
    }
    
    private void GuardaDadosAvaliacaoEquipe(boolean pAprovado, String pProblema) {

        if (pAprovado == true){
            avaliacao_Equipe.definirId_Equipe(Integer.parseInt(txtId_Equipe.getText()));
            avaliacao_Equipe.definirId_Avaliacao(Integer.parseInt(txtId_Prova.getText()));
            avaliacao_Equipe.definirPeso_Ponte(Double.parseDouble(txtPeso_Ponte.getText()));
            avaliacao_Equipe.definirPontuacao(Double.parseDouble(lblPesoSuportado.getText()));
            avaliacao_Equipe.definirProblema("");
            avaliacao_Equipe.definirData_Criacao(txtData_Criacao.getText());
            avaliacao_Equipe.definirUsuario_Criacao(Tela_Login.objMenu.mIdUsuarioLogin);
            
            if (lblAprovado.getText().equals("PESO APROVADO")){
                avaliacao_Equipe.definirAprovado(1);
            }else{
                avaliacao_Equipe.definirAprovado(0);
            } 
        }else{
            avaliacao_Equipe.definirId_Equipe(Integer.parseInt(txtId_Equipe.getText()));
            avaliacao_Equipe.definirId_Avaliacao(Integer.parseInt(txtId_Prova.getText()));
            avaliacao_Equipe.definirPeso_Ponte(Double.parseDouble(txtPeso_Ponte.getText()));
            avaliacao_Equipe.definirPontuacao(Double.parseDouble(lblPesoSuportado.getText()));
            avaliacao_Equipe.definirProblema(pProblema);

            //if (lblAprovado.getText().equals("PESO APROVADO")){
            //    avaliacao_Equipe.definirAprovado(1);
            //}else{
                avaliacao_Equipe.definirAprovado(0);
            //}
        }
        
        
    }

    private void TelaAlteracao() {

        pnlManutencao.setEnabled(true);
        tbpAvaliacoes.setSelectedIndex(1);
        txtId_Prova.setText(Integer.toString(avaliacoes.obterId_Avaliacao()));
        txtData_Criacao.setText(avaliacoes.obterData_Avaliacao());
        btAdicionarEquipe.setVisible(true);
        btExcluir.setVisible(true);
        //String data = Formatacao.ajustaDataDMA(Equipes.obterData_Criacao());
        //txtData_Criacao.setText(data);
        
        AtualizaAvaliacoesEquipes();
        
       
    }

    private void LimpaTela(boolean LimpaTudo, boolean NovoRegistro) {

        txtCampoPesquisa.setText("");
        txtId_Prova.setText("");
        txtId_Equipe.setText("");
        txtNome_Equipe.setText("");
        txtPeso_Ponte.setText("");
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        formatador.format(data);
        txtData_Criacao.setText(formatador.format(data));
        System.out.println("Data Criacao:" + txtData_Criacao.getText());
        btAdicionarEquipe.setVisible(true);
        btExcluirEquipe.setVisible(false);
            
        if (LimpaTudo == true){
            AtualizaAvaliacoes();
            jpManutencao.setEnabled(false);
            tbpAvaliacoes.setSelectedIndex(0);
            txtCampoPesquisa.requestFocus();
            btNovo.setVisible(true);
            //btAdicionar.setVisible(false);
            btAlterar.setVisible(false);
            btExcluir.setVisible(false);
        }else{
            tbpAvaliacoes.setSelectedIndex(1);
            txtNome_Equipe.requestFocus();
        }
        if (NovoRegistro == true){
            tbpAvaliacoes.setSelectedIndex(1);
            txtNome_Equipe.requestFocus();
            btNovo.setVisible(false);
            btAlterar.setVisible(false);
            btExcluir.setVisible(false);
            jpManutencao.setEnabled(true);
        }
    
   }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Avaliacoes("").setVisible(true);
            }
        });
    }
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarEquipe;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btExcluir1;
    private javax.swing.JButton btExcluirEquipe;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btIniciaTimer;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btNovo1;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btPesquisarEquipe;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JComboBox cbPesquisarPor;
    private javax.swing.JTable dtgAvaliacoes;
    private javax.swing.JTable dtgResultados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpManutencao;
    private javax.swing.JLabel lblAprovado;
    private javax.swing.JLabel lblLista1;
    private javax.swing.JLabel lblLista2;
    private javax.swing.JLabel lblLista3;
    private javax.swing.JLabel lblLista4;
    private javax.swing.JLabel lblPesoSuportado;
    private javax.swing.JLabel lblPorta;
    private javax.swing.JLabel lblPosicaoAtual;
    private javax.swing.JLabel lblTimer1;
    private javax.swing.JLayeredPane pnlConsulta;
    private javax.swing.JLayeredPane pnlManutencao;
    private javax.swing.JRadioButton rbComecandoPor;
    private javax.swing.JRadioButton rbContendo;
    private javax.swing.JTabbedPane tbpAvaliacoes;
    private javax.swing.JTextField txtCampoPesquisa;
    private javax.swing.JFormattedTextField txtData_Criacao;
    private static javax.swing.JTextField txtId_Equipe;
    private javax.swing.JTextField txtId_Prova;
    private static javax.swing.JTextField txtNome_Equipe;
    private javax.swing.JTextField txtPeso_Ponte;
    private javax.swing.JTextField txtPorta;
    // End of variables declaration//GEN-END:variables

}


