/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Clientes.java
 *
 * Created on 13/03/2011, 18:46:50
 */

package Interface;

import Modelo.Clientes;
import Modelo.ConexaoBD;
import Controle.Controla_Clientes;
import Ferramentas.CaixaDeDialogo;
import Ferramentas.Formatacao;
import Ferramentas.Validacao;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;

/**
 *
 * @author Jonas
 */
public class Tela_Clientes extends javax.swing.JFrame {
     Menu objMenu;
     public static Connection con;
     public static Statement stmt;
     public boolean vSelecao = true;
     //Clientes objCliente = null;
     Controla_Clientes ctlCliente;
     Clientes Clientes = new Clientes();
          
    /** Creates new form Clientes */
    public Tela_Clientes(String pPesquisa) {
        abreConexao();
        this.setLocation(20, 100);
        initComponents();

        ButtonGroup bg= new ButtonGroup();
        bg.add(rbComecandoPor); // jRadioButton1
        bg.add(rbContendo); // jRadioButton2

        LimpaTela(true,false);
        txtCampoPesquisa.setText(pPesquisa);
        if (!"".equals(pPesquisa)){
        System.out.print("pPesquisa = " + pPesquisa);
        cbPesquisarPor.setSelectedItem("Nome_Cliente");
        btPesquisarActionPerformed(null);
        } else {
         btCancela.setEnabled(false);
         btConfirmar.setEnabled(false);
        }

    }

//    public Clientes(Clientes objCliente) {
//        this.objCliente = objCliente;
//    }


    private void abreConexao() {
        try {
        con = ConexaoBD.getInstance().getConnection();
        stmt = con.createStatement();
        System.out.print("Conexão com Banco de Dados Criada!");
        } catch (Exception e) {
        System.out.print(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        tbpClientes = new javax.swing.JTabbedPane();
        pnlConsulta = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        rbComecandoPor = new javax.swing.JRadioButton();
        rbContendo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtgClientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbPesquisarPor = new javax.swing.JComboBox();
        txtCampoPesquisa = new javax.swing.JTextField();
        pnlManutencao = new javax.swing.JLayeredPane();
        jpManutencao = new javax.swing.JPanel();
        txtId_Cliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome_Cliente = new javax.swing.JTextField();
        txtTelefone_Cliente = new javax.swing.JFormattedTextField();
        txtTelefone_Cliente = Formatacao.getTelefone();
        jLabel5 = new javax.swing.JLabel();
        txtData_Criacao = new javax.swing.JFormattedTextField();
        txtTelefone_Cliente = Formatacao.getTelefone();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario_Criacao = new javax.swing.JFormattedTextField();
        txtTelefone_Cliente = Formatacao.getTelefone();
        jLabel7 = new javax.swing.JLabel();
        txtSituacao = new javax.swing.JFormattedTextField();
        txtTelefone_Cliente = Formatacao.getTelefone();
        jLabel9 = new javax.swing.JLabel();
        txtEndereco_Cliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBairro_Cliente = new javax.swing.JTextField();
        btConfirmar = new javax.swing.JButton();
        btCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Confirma.png"))); // NOI18N
        btAdicionar.setText("Adicionar");
        btAdicionar.setPreferredSize(new java.awt.Dimension(77, 25));
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Lapis2.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setPreferredSize(new java.awt.Dimension(77, 25));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Novo.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setPreferredSize(new java.awt.Dimension(77, 25));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Porta.PNG"))); // NOI18N
        btFechar.setText("Fechar");
        btFechar.setPreferredSize(new java.awt.Dimension(77, 25));
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Exclui.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setPreferredSize(new java.awt.Dimension(77, 25));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Mais.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovo)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 11, 0, 0);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        rbComecandoPor.setSelected(true);
        rbComecandoPor.setText("Começando Por");
        rbComecandoPor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbComecandoPorStateChanged(evt);
            }
        });

        rbContendo.setText("Contendo");
        rbContendo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbContendoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rbContendo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbComecandoPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbComecandoPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(rbContendo)
                .addContainerGap())
        );

        pnlConsulta.add(jPanel2);
        jPanel2.setBounds(430, 10, 190, 90);
        jPanel2.getAccessibleContext().setAccessibleName("Seleção");

        dtgClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dtgClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtgClientesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dtgClientesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(dtgClientes);

        pnlConsulta.add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 610, 240);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jLabel8.setText("Pesquisar Por");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPesquisar))
                    .addComponent(txtCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlConsulta.add(jPanel3);
        jPanel3.setBounds(10, 10, 420, 90);

        tbpClientes.addTab("Consulta", pnlConsulta);

        pnlManutencao.setEnabled(false);

        jpManutencao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtId_Cliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId_Cliente.setEnabled(false);

        jLabel4.setText("Nome Cliente");

        jLabel3.setText("Telefone");

        jLabel2.setText("Id Cliente");

        txtNome_Cliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel5.setText("Data Criação");

        txtData_Criacao.setEditable(false);

        jLabel6.setText("Usuário Criação");

        txtUsuario_Criacao.setEditable(false);

        jLabel7.setText("Situação");

        txtSituacao.setEditable(false);

        jLabel9.setText("Endereço");

        txtEndereco_Cliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel10.setText("Bairro");

        txtBairro_Cliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jpManutencaoLayout = new javax.swing.GroupLayout(jpManutencao);
        jpManutencao.setLayout(jpManutencaoLayout);
        jpManutencaoLayout.setHorizontalGroup(
            jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpManutencaoLayout.createSequentialGroup()
                .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpManutencaoLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpManutencaoLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpManutencaoLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jpManutencaoLayout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpManutencaoLayout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTelefone_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jpManutencaoLayout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBairro_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpManutencaoLayout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEndereco_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpManutencaoLayout.createSequentialGroup()
                        .addContainerGap(402, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUsuario_Criacao, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpManutencaoLayout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtData_Criacao, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpManutencaoLayout.setVerticalGroup(
            jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpManutencaoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndereco_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpManutencaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtData_Criacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario_Criacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpManutencaoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jpManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pnlManutencao.add(jpManutencao);
        jpManutencao.setBounds(10, 10, 610, 310);

        btConfirmar.setText("Confirma");
        btConfirmar.setEnabled(false);
        btConfirmar.setPreferredSize(new java.awt.Dimension(77, 25));
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });
        pnlManutencao.add(btConfirmar);
        btConfirmar.setBounds(430, 330, 90, 20);

        btCancela.setText("Cancela");
        btCancela.setEnabled(false);
        btCancela.setPreferredSize(new java.awt.Dimension(77, 25));
        btCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaActionPerformed(evt);
            }
        });
        pnlManutencao.add(btCancela);
        btCancela.setBounds(530, 330, 90, 20);

        tbpClientes.addTab("Manutenção", pnlManutencao);

        getContentPane().add(tbpClientes);
        tbpClientes.setBounds(10, 69, 633, 378);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int wControle = 0;

        wControle = Tela_Login.objMenu.preencheJanelas("Clientes", "I");
            if (wControle != 0){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Clientes'");
            }
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        int wControle = 0;
//
//        wControle = Tela_Login.objMenu.preencheJanelas("Clientes", "I");
//            if (wControle != 0){
//            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Clientes'");
//            }
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        int wControle = 0;

        wControle = Tela_Login.objMenu.preencheJanelas("Clientes", "I");
            if (wControle != 0){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao ativar menu 'Clientes'");
            }
        dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        int wControle = 0;
        String xMensagemValidacao = "";

        xMensagemValidacao = ValidaDados();
        if (xMensagemValidacao.equals("")){
        System.out.println("Validou Dados");

        Clientes.definirId_Cliente(Integer.parseInt(txtId_Cliente.getText()));
        //Clientes.definirNome_Cliente(txtNome_Cliente.getText());
        //Clientes.definirTelefone(txtTelefone_Cliente.getText().replace("(","").replace(")","").replace("-",""));
        GuardaDados(false);
        System.out.println("Guardou Dados");

        wControle = ctlCliente.alterarCliente();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Cliente alterado com sucesso!");
           LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao alterar cliente!");
           }
        } else {
        CaixaDeDialogo.obterinstancia().exibirMensagem("Erros de Validação: \n" + xMensagemValidacao);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        LimpaTela(true,false);
    }//GEN-LAST:event_btLimparActionPerformed

    private void dtgClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgClientesMouseClicked
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_dtgClientesMouseClicked

    private void dtgClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgClientesMousePressed
        // TODO add your handling code here:
        int wControle;
        int linhaSelecionada = dtgClientes.getSelectedRow();//pega a linha selecionada
        String coluna1 = dtgClientes.getModel().getValueAt(linhaSelecionada, 0).toString(); // Primeira coluna da linha
        
        if (dtgClientes.isColumnSelected(3)){
            tbpClientes.setSelectedIndex(1);
            txtNome_Cliente.requestFocus();
            btAlterar.setVisible(true);
            btExcluir.setVisible(true);
            btNovo.setVisible(true);
            btAdicionar.setVisible(false);

            ctlCliente = new Controla_Clientes(Clientes, dtgClientes);

            Clientes.definirId_Cliente(Integer.parseInt(coluna1));
            wControle = ctlCliente.buscarCliente();
                if (wControle < 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao buscar Cliente no BD!");
                } else {
                if (wControle == 0)
                TelaAlteracao();
                }
     }
    }//GEN-LAST:event_dtgClientesMousePressed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        // TODO add your handling code here:
        //Tela_Ordens.RecebeCliente(txtId_Cliente.getText(), txtNome_Cliente.getText(), txtTelefone_Cliente.getText());
        dispose();
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaActionPerformed
        // TODO add your handling code here:
        //Tela_Ordens.RecebeCliente("","","");
        dispose();
    }//GEN-LAST:event_btCancelaActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        LimpaTela(true,true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        int wControle = 0;
        String xMensagemValidacao = "";
        
        xMensagemValidacao = ValidaDados();
        if (xMensagemValidacao.equals("")){
        System.out.println("Validou Dados");
        GuardaDados(true);
        System.out.println("Guardou Dados");

        wControle = ctlCliente.gravarCliente();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Cliente gravado com sucesso!");
            LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao gravar cliente!");
           }
        } else {
        CaixaDeDialogo.obterinstancia().exibirMensagem("Erros de Validação: \n" + xMensagemValidacao);
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int wControle = 0;

        char wChar = 'p';
        boolean wPergunta = false;

        wPergunta = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Tem certeza de que deseja excluir o Cliente?","",wChar);

        if (wPergunta == true){
        Clientes.definirId_Cliente(Integer.parseInt(txtId_Cliente.getText()));
        Clientes.definirUsuario_Exclusao(Tela_Login.objMenu.mIdUsuarioLogin);
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        formatador.format(data);
        Clientes.definirData_Exclusao(formatador.format(data));
        wControle = ctlCliente.excluirCliente();
        if (wControle != 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Cliente excluído com sucesso!");
           LimpaTela(true,false);
        } else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao excluir cliente!");
          }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        String pTipoSelecao = "";
        if (rbComecandoPor.isSelected()){
           pTipoSelecao = "CP";
        } else {
           pTipoSelecao = "CT";
        }

        ctlCliente.PreencheClientes(cbPesquisarPor.getSelectedItem().toString(),txtCampoPesquisa.getText(), pTipoSelecao);
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void rbComecandoPorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbComecandoPorStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbComecandoPorStateChanged

    private void rbContendoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbContendoStateChanged
        // TODO add your handling code here:
        //rbComecandoPor.setSelected(false);
        //rbContendo.setSelected(true);
    }//GEN-LAST:event_rbContendoStateChanged

    private void AtualizaClientes(){
        //objClientes.setNome(txNomeMotorista.getText());
        //objClientes.definirNome_Cliente('teste');
        //objClientes.definirTelefone('teste');
        //objClientes.setCategoriaCarteira('teste');
        ctlCliente = new Controla_Clientes(Clientes, dtgClientes);
        
        //wControle = objClientes_Implem.buscaClientes();
        ctlCliente.PreencheClientes("","","");
        PreencheComboPesquisa();
    }

        private void PreencheComboPesquisa(){

        cbPesquisarPor.removeAllItems();
        if ((dtgClientes.getColumnCount() - 1) > 0){
            for (int i= 0; i < dtgClientes.getColumnCount() - 1; i++){
              cbPesquisarPor.addItem(dtgClientes.getColumnName(i));
            }
        }
        
    }

        private String ValidaDados() {
        String xMensagem = "";
        
        if(txtNome_Cliente.getText().equals("")){
        xMensagem +="Nome Cliente deve ser preenchido! \n";
        }

        if (txtTelefone_Cliente.getText().replace("(", "").replace(")","").replace("-","").replace(" ","").length() > 0){
        Validacao.validarTelefone(txtTelefone_Cliente);
            if (txtTelefone_Cliente.getText().replace("(", "").replace(")","").replace("-","").replace(" ","").length() == 0){
            xMensagem +="Telefone Cliente deve ser preenchido corretamente! \n";
            }
        }
        return xMensagem;
     }

        private void GuardaDados(boolean RegistroNovo) {

        if (RegistroNovo == true){
        System.out.println("Guardou Dados Registro Novo = true");
        Clientes.definirId_Cliente(0);
        Clientes.definirNome_Cliente(txtNome_Cliente.getText());
        Clientes.definirTelefone(txtTelefone_Cliente.getText().replace("(","").replace(")","").replace("-",""));
        Clientes.definirUsuario_Criacao(Tela_Login.objMenu.mIdUsuarioLogin);
        Clientes.definirData_Criacao(txtData_Criacao.getText());
        System.out.println("definirData_Criacao = " + txtData_Criacao.getText());
        //ctlCliente = new Controla_Clientes(Clientes, dtgClientes);
        } else {
        System.out.println("Guardou Dados Registro Novo = false");
        Clientes.definirNome_Cliente(txtNome_Cliente.getText());
        Clientes.definirTelefone(txtTelefone_Cliente.getText().replace("(","").replace(")","").replace("-",""));
        }
    }

    private void TelaAlteracao() {

        pnlManutencao.setEnabled(true);
        txtId_Cliente.setText(Integer.toString(Clientes.obterId_Cliente()));
        txtNome_Cliente.setText(Clientes.obterNome_Cliente());
        txtTelefone_Cliente.setText(Clientes.obterTelefone());

        String data = Formatacao.ajustaDataDMA(Clientes.obterData_Criacao());
        txtData_Criacao.setText(data);
        
        if (Clientes.obterData_Exclusao() == null){
            txtSituacao.setText("ATIVO");
        } else {
            txtSituacao.setText("EXCLUÍDO");
        }
    }

    private void LimpaTela(boolean LimpaTudo, boolean NovoRegistro) {

        txtCampoPesquisa.setText("");
        txtId_Cliente.setText("");
        txtNome_Cliente.setText("");
        txtTelefone_Cliente.setText("");
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        formatador.format(data);
        txtData_Criacao.setText(formatador.format(data));
        System.out.println("Data Criacao:" + txtData_Criacao.getText());
        txtUsuario_Criacao.setText(Tela_Login.objMenu.mLoginUsuario);
        btConfirmar.setEnabled(vSelecao);
        btCancela.setEnabled(vSelecao);

        if (LimpaTudo == true){
            AtualizaClientes();
            jpManutencao.setEnabled(false);
            tbpClientes.setSelectedIndex(0);
            txtCampoPesquisa.requestFocus();
            btNovo.setVisible(true);
            btAdicionar.setVisible(false);
            btAlterar.setVisible(false);
            btExcluir.setVisible(false);
        }
        if (NovoRegistro == true){
            tbpClientes.setSelectedIndex(1);
            txtNome_Cliente.requestFocus();
            btNovo.setVisible(false);
            btAdicionar.setVisible(true);
            btAlterar.setVisible(false);
            btExcluir.setVisible(false);
            jpManutencao.setEnabled(true);
        }
    
   }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Clientes("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterar;
    public static javax.swing.JButton btCancela;
    public static javax.swing.JButton btConfirmar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JComboBox cbPesquisarPor;
    private javax.swing.JTable dtgClientes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpManutencao;
    private javax.swing.JLayeredPane pnlConsulta;
    private javax.swing.JLayeredPane pnlManutencao;
    private javax.swing.JRadioButton rbComecandoPor;
    private javax.swing.JRadioButton rbContendo;
    private javax.swing.JTabbedPane tbpClientes;
    private javax.swing.JTextField txtBairro_Cliente;
    private javax.swing.JTextField txtCampoPesquisa;
    private javax.swing.JFormattedTextField txtData_Criacao;
    private javax.swing.JTextField txtEndereco_Cliente;
    private javax.swing.JTextField txtId_Cliente;
    private javax.swing.JTextField txtNome_Cliente;
    private javax.swing.JFormattedTextField txtSituacao;
    private javax.swing.JFormattedTextField txtTelefone_Cliente;
    private javax.swing.JFormattedTextField txtUsuario_Criacao;
    // End of variables declaration//GEN-END:variables

}
